# Generated by Django 4.2.16 on 2026-04-22 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0003_alter_entity_entity_name_and_more'),
        ('investments', '0003_alter_exitevent_proceeds_and_more'),
        ('accounts', '0003_fundos_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTestReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(help_text='SEBI: Financial year (e.g., FY2025-26) — annual CTR required', max_length=10)),
                ('overall_compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partially_compliant', 'Partially Compliant')], default='compliant', max_length=20)),
                ('report_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('submitted_to_trustee', 'Submitted to Trustee'), ('finalized', 'Finalized')], default='draft', max_length=25)),
                ('submitted_to_trustee_at', models.DateTimeField(blank=True, help_text='Mandatory annual submission to trustee', null=True)),
                ('trustee_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, help_text='Compliance observations and findings')),
                ('remediation_plan', models.TextField(blank=True, help_text='Plan to address non-compliance findings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_test_reports', to='funds.scheme')),
            ],
            options={
                'ordering': ['scheme', '-financial_year'],
            },
        ),
        migrations.CreateModel(
            name='SEBIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('qar', 'Quarterly Activity Report'), ('aar', 'Annual Activity Report')], help_text='SEBI: QAR (quarterly) or AAR (annual)', max_length=3)),
                ('reporting_period_start', models.DateField()),
                ('reporting_period_end', models.DateField()),
                ('due_date', models.DateField(db_index=True, help_text='SEBI: May 31 for AAR, 15 days after quarter for QAR')),
                ('filing_status', models.CharField(choices=[('not_started', 'Not Started'), ('data_collection', 'Data Collection'), ('in_review', 'In Review'), ('filed', 'Filed'), ('accepted', 'Accepted'), ('rejected', 'Rejected — Resubmission Required')], db_index=True, default='not_started', max_length=20)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('si_portal_reference_number', models.CharField(blank=True, help_text='SEBI SI Portal acknowledgement number', max_length=50)),
                ('report_data', models.JSONField(blank=True, default=dict, help_text='SEBI: Full IVCA format data — flexible schema that evolves with SEBI updates')),
                ('ivca_format_version', models.CharField(blank=True, help_text='Track which IVCA format version was used', max_length=20)),
                ('nav_reconciled_with_depository', models.BooleanField(default=False, help_text='SEBI: Must be TRUE before AAR filing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sebi_reports', to='funds.fund')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(blank=True, help_text='Scheme-level report (some reports are fund-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sebi_reports', to='funds.scheme')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='EquityThresholdAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threshold_breached', models.BooleanField(db_index=True, default=True, help_text='SEBI: Auto-set by trigger on investments table')),
                ('breach_date', models.DateField(help_text='SEBI: T+30 = custodian notification deadline')),
                ('stake_percentage', models.DecimalField(decimal_places=4, help_text='Ownership % at the time of breach', max_digits=8)),
                ('custodian_notification_deadline', models.DateField(help_text='T+30 calendar days from breach_date')),
                ('custodian_notified', models.BooleanField(default=False, help_text='SEBI: Tracked for compliance evidence')),
                ('custodian_notified_date', models.DateField(blank=True, null=True)),
                ('custodian_reference', models.CharField(blank=True, help_text='Reference number of custodian notification', max_length=100)),
                ('resolved', models.BooleanField(default=False, help_text='Whether the threshold has been resolved (e.g., stake reduced below 10%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_alerts', to='investments.investment')),
            ],
            options={
                'ordering': ['-breach_date'],
            },
        ),
        migrations.CreateModel(
            name='CTRChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_number', models.PositiveIntegerField(help_text='Sequential check number within the CTR')),
                ('regulation_reference', models.CharField(help_text='SEBI regulation reference (e.g., Reg 15(1)(a))', max_length=100)),
                ('description', models.TextField(help_text='Description of the compliance requirement')),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('not_applicable', 'Not Applicable'), ('pending_review', 'Pending Review')], default='pending_review', max_length=15)),
                ('evidence', models.TextField(blank=True, help_text='Evidence or reference supporting the compliance status')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_test_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='compliance.compliancetestreport')),
            ],
            options={
                'ordering': ['compliance_test_report', 'check_number'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compliance_type', models.CharField(choices=[('sebi_qar', 'SEBI QAR Filing'), ('sebi_aar', 'SEBI AAR Filing'), ('ctr_preparation', 'CTR Preparation'), ('gst_filing', 'GST Filing'), ('tds_filing', 'TDS Filing'), ('custodian_report', 'Custodian Report'), ('auditor_appointment', 'Auditor Appointment'), ('board_meeting', 'Board Meeting'), ('nav_declaration', 'NAV Declaration'), ('depository_reconciliation', 'Depository Reconciliation'), ('kyc_renewal', 'KYC Renewal'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(db_index=True, help_text='Indexed — only upcoming/in_progress filtered typically')),
                ('recurrence', models.CharField(choices=[('one_time', 'One-Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='one_time', max_length=15)),
                ('advance_reminder_days', models.PositiveIntegerField(default=14, help_text='Send reminder this many days before due date')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='upcoming', max_length=15)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_assignments', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(blank=True, help_text='Fund-specific deadline (null for org-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_calendar', to='funds.fund')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_calendar', to='accounts.organization')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_calendar', to='funds.scheme')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='AMLDueDiligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_land_border_country_investor', models.BooleanField(db_index=True, default=False, help_text='SEBI: Auto-flagged by trigger — China, Pakistan, Bangladesh, etc.')),
                ('exceeds_50pct_threshold', models.BooleanField(default=False, help_text='SEBI: If ≥50% corpus from land-border investors — triggers enhanced scrutiny')),
                ('beneficial_owner_details', models.JSONField(blank=True, default=dict, help_text='UBO information — flexible structure for complex ownership chains')),
                ('beneficial_owner_identified', models.BooleanField(default=False)),
                ('risk_rating', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('very_high', 'Very High')], default='normal', max_length=10)),
                ('risk_assessment_date', models.DateField(blank=True, null=True)),
                ('risk_notes', models.TextField(blank=True)),
                ('custodian_reported', models.BooleanField(default=False, help_text='SEBI: Monthly custodian report filed')),
                ('custodian_report_date', models.DateField(blank=True, null=True)),
                ('str_filed', models.BooleanField(default=False)),
                ('str_reference', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AML due diligence',
                'verbose_name_plural': 'AML due diligence records',
                'ordering': ['investor'],
            },
        ),
    ]
