# Generated by Django 4.2.16 on 2026-04-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('lp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amlduediligence',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_records', to='lp.investor'),
        ),
        migrations.AddIndex(
            model_name='sebireport',
            index=models.Index(fields=['fund', '-due_date'], name='compliance__fund_id_689996_idx'),
        ),
        migrations.AddIndex(
            model_name='sebireport',
            index=models.Index(fields=['filing_status'], name='compliance__filing__e9a213_idx'),
        ),
        migrations.AddIndex(
            model_name='equitythresholdalert',
            index=models.Index(fields=['threshold_breached'], name='compliance__thresho_d47929_idx'),
        ),
        migrations.AddIndex(
            model_name='equitythresholdalert',
            index=models.Index(fields=['custodian_notified'], name='compliance__custodi_c13e5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancetestreport',
            unique_together={('scheme', 'financial_year')},
        ),
        migrations.AddIndex(
            model_name='compliancecalendar',
            index=models.Index(fields=['due_date', 'status'], name='compliance__due_dat_2ff92b_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecalendar',
            index=models.Index(fields=['organization', 'status'], name='compliance__organiz_8781d1_idx'),
        ),
    ]
