# Generated by Django 4.2.16 on 2026-05-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_alter_entity_gstin_alter_entity_organization_and_more'),
        ('compliance', '0005_escalation_severity_combined_score'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ppmamendment',
            name='unique_fund_amendment_number',
        ),
        migrations.RenameIndex(
            model_name='circularaction',
            new_name='compliance__status_379fa1_idx',
            old_name='compliance_action_status_idx',
        ),
        migrations.RenameIndex(
            model_name='circularaction',
            new_name='compliance__due_dat_f44766_idx',
            old_name='compliance_action_due_idx',
        ),
        migrations.RenameIndex(
            model_name='portfoliocompanycompliance',
            new_name='compliance__portfol_4decb8_idx',
            old_name='compl_pc_rag_idx',
        ),
        migrations.RenameIndex(
            model_name='portfoliocompanycompliance',
            new_name='compliance__deadlin_80b561_idx',
            old_name='compl_deadline_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sebicircular',
            new_name='compliance__circula_0fb80b_idx',
            old_name='compliance_circular_date_idx',
        ),
        migrations.RenameIndex(
            model_name='sebicircular',
            new_name='compliance__impact__b7b355_idx',
            old_name='compliance_impact_level_idx',
        ),
        migrations.AlterField(
            model_name='circularaction',
            name='action_description',
            field=models.TextField(help_text='Detailed description of the required action'),
        ),
        migrations.AlterField(
            model_name='circularaction',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Evidence or notes on how the action was completed'),
        ),
        migrations.AlterField(
            model_name='circularaction',
            name='deferred_reason',
            field=models.TextField(blank=True, help_text='Reason for deferral if status is deferred'),
        ),
        migrations.AlterField(
            model_name='circularaction',
            name='due_date',
            field=models.DateField(blank=True, help_text='Deadline for this specific action (may differ from circular deadline)', null=True),
        ),
        migrations.AlterField(
            model_name='circularaction',
            name='fund',
            field=models.ForeignKey(blank=True, help_text='Fund-specific action (null = applies to all org funds)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circular_actions', to='funds.fund'),
        ),
        migrations.AlterField(
            model_name='equitythresholdalert',
            name='severity',
            field=models.CharField(choices=[('urgent', 'URGENT — Breach >25%, immediate action required'), ('high', 'HIGH — Breach >10%, action within 7 days'), ('medium', 'MEDIUM — Approaching breach, monitor closely')], default='high', help_text='Auto-classified by stake_percentage at breach time', max_length=8),
        ),
        migrations.AlterField(
            model_name='escalationlog',
            name='level',
            field=models.PositiveSmallIntegerField(help_text='1=GP Partner, 2=CFO, 3=Compliance Officer'),
        ),
        migrations.AlterField(
            model_name='escalationlog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='femacompliance',
            name='form_type',
            field=models.CharField(choices=[('fc_gpr', 'FC-GPR (Foreign Currency — Gross Provisional Return)'), ('apr', 'APR (Annual Performance Report)'), ('fc_trs', 'FC-TRS (Transfer of Shares)'), ('llp_i', 'LLP-I (FDI in LLP)'), ('llp_ii', 'LLP-II (Disinvestment from LLP)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='femacompliance',
            name='rbi_arn',
            field=models.CharField(blank=True, help_text='RBI Acknowledgement Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='fundcompliancescore',
            name='combined_score',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Weighted composite 0-100', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fundcompliancescore',
            name='score_detail',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='portfoliocompanycompliance',
            name='deadline',
            field=models.DateField(help_text='Filing/deposit deadline'),
        ),
        migrations.AlterField(
            model_name='portfoliocompanycompliance',
            name='obligation_name',
            field=models.CharField(help_text='e.g., "GST GSTR-3B — April 2025", "EPF Deposit — March 2025"', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliocompanycompliance',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty imposed for late filing (if any)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfoliocompliancescore',
            name='compliance_score',
            field=models.DecimalField(decimal_places=2, help_text='0 = fully non-compliant, 100 = fully compliant', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='board_approval_date',
            field=models.DateField(blank=True, help_text='Date board/investment committee approved the amendment', null=True),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='description',
            field=models.TextField(help_text='Detailed description of what changed and why'),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='document_url',
            field=models.URLField(blank=True, help_text='Link to the amended PPM document', max_length=500),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Date the amendment becomes effective', null=True),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='investor_exit_window_days',
            field=models.PositiveIntegerField(default=30, help_text='Days investors have to exit after notification (typically 30 days)'),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='investor_exit_window_expiry',
            field=models.DateField(blank=True, help_text='Last date for investors to exercise exit right', null=True),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='investor_notification_date',
            field=models.DateField(blank=True, help_text='Date investors were notified — they have an exit window', null=True),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='scheme',
            field=models.ForeignKey(blank=True, help_text='Scheme-level PPM amendment (null = fund-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppm_amendments', to='funds.scheme'),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='sebi_acknowledgement_number',
            field=models.CharField(blank=True, help_text='SEBI acknowledgement number for the filing', max_length=50),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='sebi_filing_date',
            field=models.DateField(blank=True, help_text='SEBI: Must be filed within 21 days of approval', null=True),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='title',
            field=models.CharField(help_text='Short title of the amendment', max_length=255),
        ),
        migrations.AlterField(
            model_name='ppmamendment',
            name='trustee_approval_date',
            field=models.DateField(blank=True, help_text='Date trustee approved the amendment', null=True),
        ),
        migrations.AlterField(
            model_name='sebicircular',
            name='ai_parsed',
            field=models.BooleanField(default=False, help_text='Whether the circular has been parsed by AI to extract action items'),
        ),
        migrations.AlterField(
            model_name='sebicircular',
            name='circular_date',
            field=models.DateField(help_text='Date of the circular'),
        ),
        migrations.AlterField(
            model_name='sebicircular',
            name='circular_number',
            field=models.CharField(help_text='SEBI circular number e.g. SEBI/HO/AFD/SEC-1/P/CIR/2024/104', max_length=100),
        ),
        migrations.AlterField(
            model_name='sebicircular',
            name='compliance_deadline',
            field=models.DateField(blank=True, help_text='Deadline by which all action items must be completed', null=True),
        ),
        migrations.AlterField(
            model_name='sebicircular',
            name='full_text',
            field=models.TextField(blank=True, help_text='Full text of the circular (for AI parsing)'),
        ),
        migrations.AlterField(
            model_name='sebicircular',
            name='is_superseded',
            field=models.BooleanField(default=False, help_text='Whether this circular has been superseded by a newer one'),
        ),
        migrations.AlterField(
            model_name='sebicircular',
            name='sebi_url',
            field=models.URLField(blank=True, help_text='URL to the circular on SEBI website', max_length=500),
        ),
        migrations.AlterField(
            model_name='sebicircular',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated or manually written summary of key requirements'),
        ),
        migrations.AlterField(
            model_name='sebicircular',
            name='title',
            field=models.CharField(help_text='Title / subject of the circular', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='ppmamendment',
            unique_together={('fund', 'amendment_number')},
        ),
    ]
