# Generated by Django 4.2.16 on 2026-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_consolidation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetvsactual',
            name='actual_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount in INR (Lakhs)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='budgetvsactual',
            name='budget_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budgeted amount in INR (Lakhs)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='budgetvsactual',
            name='is_favorable',
            field=models.BooleanField(blank=True, help_text='True if variance is favorable (revenue lines: actual>budget; cost lines: actual<budget)', null=True),
        ),
        migrations.AlterField(
            model_name='budgetvsactual',
            name='period_month',
            field=models.PositiveIntegerField(blank=True, help_text='Month 1-12 for monthly; null for quarterly/annual', null=True),
        ),
        migrations.AlterField(
            model_name='budgetvsactual',
            name='period_quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='Quarter if monthly is null', max_length=2),
        ),
        migrations.AlterField(
            model_name='budgetvsactual',
            name='period_year',
            field=models.PositiveIntegerField(help_text='Financial year e.g. 2025'),
        ),
        migrations.AlterField(
            model_name='budgetvsactual',
            name='variance_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual - Budget (positive = over-achievement for revenue)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='budgetvsactual',
            name='variance_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='(Actual - Budget) / |Budget| × 100', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='consolidatedmis',
            name='company_count',
            field=models.IntegerField(default=0, help_text='Number of companies contributing'),
        ),
        migrations.AlterField(
            model_name='consolidatedmis',
            name='line_item',
            field=models.CharField(choices=[('revenue', 'Revenue / Net Sales'), ('other_income', 'Other Income'), ('total_revenue', 'Total Revenue'), ('cogs', 'Cost of Goods Sold (COGS)'), ('gross_profit', 'Gross Profit'), ('employee_cost', 'Employee / Payroll Cost'), ('marketing_cost', 'Marketing & Sales Cost'), ('rd_cost', 'R&D Cost'), ('g_and_a', 'G&A / Overheads'), ('total_opex', 'Total Operating Expenses'), ('ebitda', 'EBITDA'), ('depreciation', 'Depreciation & Amortisation'), ('ebit', 'EBIT'), ('finance_cost', 'Finance Cost / Interest'), ('pbt', 'Profit Before Tax (PBT)'), ('tax', 'Tax (Current + Deferred)'), ('pat', 'Profit After Tax (PAT)'), ('total_assets', 'Total Assets'), ('total_debt', 'Total Debt'), ('cash_and_equivalents', 'Cash & Equivalents'), ('net_worth', 'Net Worth / Equity')], max_length=30),
        ),
    ]
