# Generated by Django 4.2.16 on 2026-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_consolidation', '0003_budgetvsactual_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetvsactual',
            name='line_item',
            field=models.CharField(choices=[('revenue', 'Revenue / Net Sales'), ('other_income', 'Other Income'), ('total_revenue', 'Total Revenue'), ('cogs', 'Cost of Goods Sold (COGS)'), ('gross_profit', 'Gross Profit'), ('employee_cost', 'Employee / Payroll Cost'), ('marketing_cost', 'Marketing & Sales Cost'), ('rd_cost', 'R&D Cost'), ('g_and_a', 'G&A / Overheads'), ('total_opex', 'Total Operating Expenses'), ('ebitda', 'EBITDA'), ('depreciation', 'Depreciation & Amortisation'), ('ebit', 'EBIT'), ('finance_cost', 'Finance Cost / Interest'), ('pbt', 'Profit Before Tax (PBT)'), ('tax', 'Tax (Current + Deferred)'), ('pat', 'Profit After Tax (PAT)'), ('total_assets', 'Total Assets'), ('total_debt', 'Total Debt'), ('cash_and_equivalents', 'Cash & Equivalents'), ('net_worth', 'Net Worth / Equity'), ('capex', 'Capex / Capital Expenditure'), ('working_capital', 'Working Capital'), ('net_working_capital', 'Net Working Capital'), ('dividend', 'Dividend Paid'), ('other_cost', 'Other Cost / Expense'), ('net_irr', 'Net IRR (Fund Level)'), ('tvpi', 'TVPI (Total Value to Paid-In)'), ('portfolio_fv', 'Portfolio Fair Value')], max_length=30),
        ),
        migrations.AlterField(
            model_name='consolidatedmis',
            name='line_item',
            field=models.CharField(choices=[('revenue', 'Revenue / Net Sales'), ('other_income', 'Other Income'), ('total_revenue', 'Total Revenue'), ('cogs', 'Cost of Goods Sold (COGS)'), ('gross_profit', 'Gross Profit'), ('employee_cost', 'Employee / Payroll Cost'), ('marketing_cost', 'Marketing & Sales Cost'), ('rd_cost', 'R&D Cost'), ('g_and_a', 'G&A / Overheads'), ('total_opex', 'Total Operating Expenses'), ('ebitda', 'EBITDA'), ('depreciation', 'Depreciation & Amortisation'), ('ebit', 'EBIT'), ('finance_cost', 'Finance Cost / Interest'), ('pbt', 'Profit Before Tax (PBT)'), ('tax', 'Tax (Current + Deferred)'), ('pat', 'Profit After Tax (PAT)'), ('total_assets', 'Total Assets'), ('total_debt', 'Total Debt'), ('cash_and_equivalents', 'Cash & Equivalents'), ('net_worth', 'Net Worth / Equity'), ('capex', 'Capex / Capital Expenditure'), ('working_capital', 'Working Capital'), ('net_working_capital', 'Net Working Capital'), ('dividend', 'Dividend Paid'), ('other_cost', 'Other Cost / Expense'), ('net_irr', 'Net IRR (Fund Level)'), ('tvpi', 'TVPI (Total Value to Paid-In)'), ('portfolio_fv', 'Portfolio Fair Value')], max_length=30),
        ),
    ]
