# Generated by Django 4.2.16 on 2026-05-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_kpidefinition_is_system_kpi_and_more'),
        ('emailingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmissubmission',
            name='email_uid',
            field=models.CharField(help_text='IMAP UID of the email — used to detect duplicates', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmissubmission',
            name='portfolio_company',
            field=models.ForeignKey(blank=True, help_text='Matched portfolio company (Gemini semantic match on sender + subject)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_submissions', to='investments.portfoliocompany'),
        ),
        migrations.AlterField(
            model_name='emailmissubmission',
            name='received_at',
            field=models.DateTimeField(help_text='When the email arrived in the mailbox'),
        ),
        migrations.AlterField(
            model_name='emailmissubmission',
            name='sender_email',
            field=models.EmailField(help_text='Sender email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='mailboxpolllog',
            name='emails_new',
            field=models.IntegerField(default=0, help_text='New emails not seen before'),
        ),
    ]
