"""
Comprehensive MIS Report Generator — 25-50 page fund-level PDF.

Generates a concise MIS package with dashboard-style consolidated tables:
  1. Cover Page & Table of Contents
  2. Fund Overview & Executive Summary
  3. Portfolio Company P&L (consolidated table — one row per company)
  4. Budget vs Actual / Variance Analysis
  5. Consolidated Fund P&L (fund-level rollup)
  6. Balance Sheet Snapshot (consolidated)
  7. Cash Flow Statement (consolidated)
  8. Burn & Runway Analysis
  9. SaaS Metrics
 10. KPI Dashboard (company matrix)
 11. Quoted vs Unquoted Breakdown
 12. Investments Summary
 13. Valuation Summary (IPEV)
 14. NAV & Unit Value History
 15. Capital Calls
 16. Distributions
 17. LP Capital Accounts
 18. Fund Ledger (recent entries)
 19. Trial Balance Snapshot
 20. Investor Summary (SaaS / Sector)
 21. Waterfall & Carry Schedule
 22. Anomaly Alerts & Risk Flags
 23. Disclaimer & Notes

Uses ReportLab for professional-grade PDF output with CONFIDENTIAL watermark.
"""
import io
import logging
from collections import defaultdict
from datetime import date
from decimal import Decimal

from django.conf import settings
from django.core.files.base import ContentFile
from django.utils import timezone

logger = logging.getLogger(__name__)

# ── Colours & Styles ────────────────────────────────────────────────────

_DARK_BLUE = None
_MID_BLUE = None
_LIGHT_BG = None
_ACCENT_GREEN = None
_ACCENT_RED = None
_DARK_GREY = None


def _init_colors():
    global _DARK_BLUE, _MID_BLUE, _LIGHT_BG, _ACCENT_GREEN, _ACCENT_RED, _DARK_GREY
    from reportlab.lib import colors
    _DARK_BLUE = colors.HexColor('#003366')
    _MID_BLUE = colors.HexColor('#0066CC')
    _LIGHT_BG = colors.HexColor('#F5F8FF')
    _ACCENT_GREEN = colors.HexColor('#059669')
    _ACCENT_RED = colors.HexColor('#DC2626')
    _DARK_GREY = colors.HexColor('#4B5563')


def _fmt_cr(val, dash='—'):
    """Format a Decimal/float as Rs.XX.XX Cr."""
    if val is None:
        return dash
    try:
        v = float(val)
        return f'Rs.{v:,.2f} Cr'
    except (TypeError, ValueError):
        return dash


def _fmt_pct(val, dash='—'):
    if val is None:
        return dash
    try:
        return f'{float(val):,.1f}%'
    except (TypeError, ValueError):
        return dash


def _fmt_num(val, dash='—'):
    if val is None:
        return dash
    try:
        return f'{float(val):,.2f}'
    except (TypeError, ValueError):
        return dash


def _fmt_date(val, dash='—'):
    if val is None:
        return dash
    return str(val)


# ── Watermark ───────────────────────────────────────────────────────────

def _draw_watermark_bottom(canvas, doc, text='CONFIDENTIAL'):
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    canvas.saveState()
    canvas.setFont('Helvetica-Bold', 18)
    canvas.setFillAlpha(0.12)
    canvas.setFillColor(colors.HexColor('#003366'))
    canvas.drawRightString(doc.pagesize[0] - 2 * cm, 2.0 * cm, text)
    canvas.restoreState()


def _page_header_footer(canvas, doc, fund_name, report_date):
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    width, height = doc.pagesize

    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor('#003366'))
    canvas.setLineWidth(0.5)
    canvas.line(2 * cm, height - 1.5 * cm, width - 2 * cm, height - 1.5 * cm)
    canvas.setFont('Helvetica', 7)
    canvas.setFillColor(colors.HexColor('#6B7280'))
    canvas.drawString(2 * cm, height - 1.3 * cm, f'{fund_name} — Comprehensive MIS Report')
    canvas.drawRightString(width - 2 * cm, height - 1.3 * cm, report_date)

    canvas.line(2 * cm, 1.5 * cm, width - 2 * cm, 1.5 * cm)
    canvas.setFont('Helvetica', 7)
    canvas.drawString(2 * cm, 1.0 * cm, 'Generated by TrackFundAI · Confidential · For Authorised Recipients Only')
    canvas.drawRightString(width - 2 * cm, 1.0 * cm, f'Page {doc.page}')
    canvas.restoreState()

    if doc.page <= 2:
        _draw_watermark_bottom(canvas, doc)


# ── Main Generator ──────────────────────────────────────────────────────

def generate_comprehensive_mis(fund, user=None):
    """
    Generate a comprehensive MIS report PDF for a fund.
    Returns: (pdf_bytes: bytes, report_data: dict)
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, PageBreak, KeepTogether
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
    except ImportError:
        logger.error('ReportLab not installed')
        return None, {'error': 'ReportLab not installed'}

    _init_colors()

    org = fund.organization
    report_date_str = date.today().strftime('%d %B %Y')

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=2.2 * cm, bottomMargin=2.2 * cm,
        leftMargin=1.5 * cm, rightMargin=1.5 * cm,
    )

    PAGE_W = A4[0] - 3 * cm  # usable width

    styles = getSampleStyleSheet()

    cover_title = ParagraphStyle('cover_title', parent=styles['Heading1'],
                                  fontSize=28, textColor=_DARK_BLUE,
                                  spaceAfter=8, alignment=TA_CENTER)
    cover_sub = ParagraphStyle('cover_sub', parent=styles['Normal'],
                                fontSize=14, textColor=_MID_BLUE,
                                alignment=TA_CENTER)
    cover_info = ParagraphStyle('cover_info', parent=styles['Normal'],
                                 fontSize=10, textColor=_DARK_GREY,
                                 alignment=TA_CENTER, leading=16)
    section_h = ParagraphStyle('section_h', parent=styles['Heading1'],
                                fontSize=14, textColor=_DARK_BLUE,
                                spaceBefore=12, spaceAfter=6)
    subsection_h = ParagraphStyle('subsection_h', parent=styles['Heading2'],
                                   fontSize=10, textColor=_MID_BLUE,
                                   spaceBefore=8, spaceAfter=3)
    body = ParagraphStyle('body', parent=styles['Normal'],
                           fontSize=8, leading=11, textColor=colors.HexColor('#1F2937'),
                           alignment=TA_JUSTIFY)
    small = ParagraphStyle('small', parent=styles['Normal'],
                            fontSize=7, leading=10, textColor=_DARK_GREY)

    def make_table(data, col_widths=None, header_bg=None, font_size=7):
        if not data or len(data) < 2:
            return Spacer(1, 0)
        if header_bg is None:
            header_bg = _DARK_BLUE
        t = Table(data, colWidths=col_widths, repeatRows=1)
        style_cmds = [
            ('BACKGROUND', (0, 0), (-1, 0), header_bg),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), font_size),
            ('FONTSIZE', (0, 1), (-1, -1), font_size),
            ('GRID', (0, 0), (-1, -1), 0.3, colors.HexColor('#D1D5DB')),
            ('PADDING', (0, 0), (-1, -1), 3),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, _LIGHT_BG]),
        ]
        t.setStyle(TableStyle(style_cmds))
        return t

    def add_hr():
        return HRFlowable(width='100%', thickness=0.5, color=colors.HexColor('#D1D5DB'),
                          spaceAfter=6, spaceBefore=3)

    # Collect all data
    data = _collect_all_data(fund, org)
    story = []
    report_summary = {
        'fund_name': fund.name,
        'report_date': report_date_str,
        'sections': [],
    }

    # ─── 1. COVER PAGE ─────────────────────────────────────────────────
    story.append(Spacer(1, 4 * cm))
    story.append(Paragraph('COMPREHENSIVE MIS REPORT', cover_title))
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(fund.name, ParagraphStyle('fn', parent=cover_sub, fontSize=20)))
    story.append(Spacer(1, 0.3 * cm))
    scheme_names = ', '.join(data.get('scheme_names', []))
    if scheme_names:
        story.append(Paragraph(scheme_names, cover_sub))
    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width='60%', thickness=1.5, color=_DARK_BLUE, hAlign='CENTER'))
    story.append(Spacer(1, 1 * cm))

    cover_lines = [
        f'SEBI Registration: {fund.sebi_registration_number or "Pending"}',
        f'Fund Category: Category {fund.fund_category.name if hasattr(fund, "fund_category") and fund.fund_category else "II"} AIF',
        f'Report Date: {report_date_str}',
        f'Prepared by: TrackFundAI Automated Reporting Engine',
        f'Classification: CONFIDENTIAL',
    ]
    story.append(Paragraph('<br/>'.join(cover_lines), cover_info))
    story.append(Spacer(1, 2 * cm))
    story.append(Paragraph(
        'This report is generated automatically from fund data in TrackFundAI. '
        'Intended solely for authorised fund managers and investors.',
        ParagraphStyle('cov_disc', parent=small, alignment=TA_CENTER)
    ))
    story.append(PageBreak())

    # ─── 2. TABLE OF CONTENTS ─────────────────────────────────────────
    story.append(Paragraph('Table of Contents', section_h))
    story.append(Spacer(1, 0.3 * cm))
    toc_items = [
        '1. Fund Overview & Executive Summary',
        '2. Quarterly LP Letter',
        '3. Portfolio Company P&L',
        '4. Budget vs Actual / Variance',
        '5. Consolidated Fund P&L',
        '6. Balance Sheet Snapshot',
        '7. Cash Flow Statement',
        '8. Burn & Runway Analysis',
        '9. SaaS Metrics',
        '10. KPI Dashboard',
        '11. Quoted vs Unquoted',
        '12. Investments Summary',
        '13. Valuation Summary (IPEV)',
        '14. NAV & Unit Value',
        '15. Capital Calls',
        '16. Distributions',
        '17. LP Capital Accounts',
        '18. Fund Ledger',
        '19. Trial Balance',
        '20. Investor Summary (SaaS / Sector)',
        '21. Waterfall & Carry Schedule',
        '22. Anomaly Alerts & Risk Flags',
        '23. Disclaimer & Notes',
    ]
    for item in toc_items:
        story.append(Paragraph(item, ParagraphStyle(
            'toc', parent=body, fontSize=10, spaceBefore=3, spaceAfter=3,
            textColor=_DARK_BLUE
        )))
    story.append(PageBreak())

    # ─── 3. FUND OVERVIEW & EXECUTIVE SUMMARY ─────────────────────────
    story.append(Paragraph('1. Fund Overview & Executive Summary', section_h))
    story.append(add_hr())

    fund_details = [
        ['Parameter', 'Details'],
        ['Fund Name', fund.name],
        ['SEBI Reg. No.', fund.sebi_registration_number or '—'],
        ['Fund Category', f'Category {fund.fund_category.name}' if hasattr(fund, 'fund_category') and fund.fund_category else '—'],
        ['Schemes', scheme_names or '—'],
        ['Portfolio Companies', str(data.get('company_count', 0))],
        ['Total Investors', str(data.get('investor_count', 0))],
        ['Total AUM (Latest NAV)', _fmt_cr(data.get('latest_aum'))],
        ['NAV per Unit', _fmt_num(data.get('nav_per_unit'))],
        ['Total Invested', _fmt_cr(data.get('total_invested'))],
        ['Total Fair Value', _fmt_cr(data.get('total_fv'))],
        ['Aggregate MOIC', _fmt_num(data.get('aggregate_moic'))],
        ['Hurdle Rate', _fmt_pct(data.get('hurdle_rate'))],
        ['Carry %', _fmt_pct(data.get('carry_pct'))],
    ]
    story.append(make_table(fund_details, col_widths=[6 * cm, PAGE_W - 6 * cm]))
    story.append(Spacer(1, 0.4 * cm))

    exec_summary = _generate_executive_summary(data)
    story.append(Paragraph('Executive Summary', subsection_h))
    story.append(Paragraph(exec_summary, body))
    story.append(PageBreak())

    # ─── 3A. QUARTERLY LP LETTER ──────────────────────────────────────
    story.append(Paragraph('2. Quarterly LP Letter', section_h))
    story.append(add_hr())
    lp_letter = _generate_lp_letter(data, fund, report_date_str)
    story.append(Paragraph(lp_letter, body))
    story.append(PageBreak())

    # ─── 4. PORTFOLIO COMPANY P&L ─────────────────────────────────────
    # Dashboard-style consolidated table: one row per company, latest period
    story.append(Paragraph('3. Portfolio Company P&L', section_h))
    story.append(add_hr())
    story.append(Paragraph(
        'Consolidated P&L showing the latest period data for each portfolio company. '
        'Matching the dashboard Company P&L view.',
        small
    ))
    story.append(Spacer(1, 0.2 * cm))

    pl_consolidated = data.get('pl_consolidated', [])
    if pl_consolidated:
        cw = [0.7 * cm, 4.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2 * cm, 2.3 * cm]
        pl_table = [['#', 'Company', 'Revenue (Cr)', 'EBITDA (Cr)', 'PAT (Cr)',
                      'EBITDA %', 'Period']]
        for i, r in enumerate(pl_consolidated, 1):
            pl_table.append([
                str(i),
                r.get('company', '—')[:30],
                _fmt_cr(r.get('revenue')),
                _fmt_cr(r.get('ebitda')),
                _fmt_cr(r.get('pat')),
                _fmt_pct(r.get('ebitda_pct')),
                r.get('period', '—'),
            ])
        story.append(make_table(pl_table, col_widths=cw))
        # Summary row
        total_rev = sum(r.get('revenue') or 0 for r in pl_consolidated)
        total_ebitda = sum(r.get('ebitda') or 0 for r in pl_consolidated)
        total_pat = sum(r.get('pat') or 0 for r in pl_consolidated)
        agg_ebitda_pct = (total_ebitda / total_rev * 100) if total_rev else 0
        story.append(Paragraph(
            f'Total — Revenue: {_fmt_cr(total_rev)} | EBITDA: {_fmt_cr(total_ebitda)} '
            f'| PAT: {_fmt_cr(total_pat)} | EBITDA%: {agg_ebitda_pct:.1f}% '
            f'| {len(pl_consolidated)} companies',
            ParagraphStyle('pl_sum', parent=body, fontName='Helvetica-Bold', fontSize=7)
        ))
    else:
        story.append(Paragraph('No P&L data available. Import fund Excel files to populate.', body))
    story.append(PageBreak())

    # ─── 5. BUDGET VS ACTUAL / VARIANCE ───────────────────────────────
    story.append(Paragraph('4. Budget vs Actual / Variance', section_h))
    story.append(add_hr())

    bva_summary = data.get('bva_summary', [])
    if bva_summary:
        bva_cw = [3.5 * cm, 2.8 * cm, 2.2 * cm, 2.2 * cm, 2.2 * cm, 1.8 * cm, 1.8 * cm]
        bva_table = [['Company', 'Line Item', 'Budget (Cr)', 'Actual (Cr)',
                       'Variance (Cr)', 'Var %', 'Favorable']]
        for r in bva_summary[:80]:
            bva_table.append([
                r.get('company', '')[:25],
                r.get('line_item', ''),
                _fmt_cr(r.get('budget')),
                _fmt_cr(r.get('actual')),
                _fmt_cr(r.get('variance')),
                _fmt_pct(r.get('variance_pct')),
                'Yes' if r.get('is_favorable') else ('No' if r.get('is_favorable') is False else '—'),
            ])
        story.append(make_table(bva_table, col_widths=bva_cw))
    else:
        story.append(Paragraph('No Budget vs Actual records found.', body))
    story.append(PageBreak())

    # ─── 6. CONSOLIDATED FUND P&L ─────────────────────────────────────
    story.append(Paragraph('5. Consolidated Fund P&L', section_h))
    story.append(add_hr())
    story.append(Paragraph(
        'Fund-level monthly P&L rollup aggregating all portfolio companies.',
        small
    ))
    story.append(Spacer(1, 0.2 * cm))

    fund_pl = data.get('fund_pl', [])
    if fund_pl:
        fpl_cw = [2.5 * cm, 3 * cm, 3 * cm, 3 * cm, 2.5 * cm, 2.5 * cm]
        fpl_table = [['Period', 'Revenue (Cr)', 'EBITDA (Cr)', 'PAT (Cr)',
                       'EBITDA %', '# Companies']]
        for r in fund_pl:
            fpl_table.append([
                r.get('period', '—'),
                _fmt_cr(r.get('revenue')),
                _fmt_cr(r.get('ebitda')),
                _fmt_cr(r.get('pat')),
                _fmt_pct(r.get('ebitda_pct')),
                str(r.get('company_count', '—')),
            ])
        story.append(make_table(fpl_table, col_widths=fpl_cw))
    else:
        story.append(Paragraph('No consolidated fund P&L data available.', body))
    story.append(Spacer(1, 0.3 * cm))

    # ─── 7. BALANCE SHEET SNAPSHOT ────────────────────────────────────
    story.append(Paragraph('6. Balance Sheet Snapshot', section_h))
    story.append(add_hr())

    bs_consolidated = data.get('bs_consolidated', [])
    if bs_consolidated:
        bs_cw = [0.7 * cm, 4 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.3 * cm]
        bs_table = [['#', 'Company', 'Total Assets (Cr)', 'Net Worth (Cr)',
                      'Total Debt (Cr)', 'Cash (Cr)', 'Period']]
        for i, r in enumerate(bs_consolidated, 1):
            bs_table.append([
                str(i),
                r.get('company', '—')[:28],
                _fmt_cr(r.get('total_assets')),
                _fmt_cr(r.get('net_worth')),
                _fmt_cr(r.get('total_debt')),
                _fmt_cr(r.get('cash')),
                r.get('period', '—'),
            ])
        story.append(make_table(bs_table, col_widths=bs_cw))
    else:
        story.append(Paragraph('No Balance Sheet data available.', body))
    story.append(Spacer(1, 0.3 * cm))

    # ─── 8. CASH FLOW STATEMENT ──────────────────────────────────────
    story.append(Paragraph('7. Cash Flow Statement', section_h))
    story.append(add_hr())

    cf_consolidated = data.get('cf_consolidated', [])
    cf_fund_level = data.get('cf_fund_level', False)
    if cf_consolidated and cf_fund_level:
        # Fund-level cash flow from FundLedger
        cf_period = data.get('cf_period', '—')
        story.append(Paragraph(
            f'Fund-level cash flow statement derived from fund ledger entries. Period: {cf_period}',
            small
        ))
        story.append(Spacer(1, 0.2 * cm))
        cf_cw = [6 * cm, 3 * cm, 4 * cm, 3.5 * cm]
        cf_table = [['Item', 'Category', 'Amount (Cr)', 'Flow']]
        for r in cf_consolidated:
            amt = r.get('amount', 0)
            flow = 'Inflow' if amt > 0 else ('Outflow' if amt < 0 else '—')
            cf_table.append([
                r.get('item', '—'),
                r.get('category', '—'),
                _fmt_cr(abs(amt) if amt else 0),
                flow,
            ])
        story.append(make_table(cf_table, col_widths=cf_cw))
    elif cf_consolidated:
        cf_cw = [0.7 * cm, 4.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 1.8 * cm]
        cf_table = [['#', 'Company', 'Cash (Cr)', 'Finance Cost (Cr)',
                      'CapEx (Cr)', 'Dividend (Cr)', 'Period']]
        for i, r in enumerate(cf_consolidated, 1):
            cf_table.append([
                str(i),
                r.get('company', '—')[:28],
                _fmt_cr(r.get('cash')),
                _fmt_cr(r.get('finance_cost')),
                _fmt_cr(r.get('capex')),
                _fmt_cr(r.get('dividend')),
                r.get('period', '—'),
            ])
        story.append(make_table(cf_table, col_widths=cf_cw))
    else:
        story.append(Paragraph('No Cash Flow data available.', body))
    story.append(PageBreak())

    # ─── 9. BURN & RUNWAY ANALYSIS ────────────────────────────────────
    story.append(Paragraph('8. Burn & Runway Analysis', section_h))
    story.append(add_hr())

    burn_data = data.get('burn_runway', [])
    if burn_data:
        br_cw = [0.7 * cm, 4 * cm, 2.5 * cm, 2.5 * cm, 2.8 * cm, 2.5 * cm, 2 * cm]
        br_table = [['#', 'Company', 'Gross Burn (Cr/mo)', 'Net Burn (Cr/mo)',
                      'Cash Balance (Cr)', 'Runway (months)', 'Period']]
        for i, r in enumerate(burn_data, 1):
            br_table.append([
                str(i),
                r.get('company', '—')[:28],
                _fmt_cr(r.get('gross_burn')),
                _fmt_cr(r.get('net_burn')),
                _fmt_cr(r.get('cash_balance')),
                str(r.get('runway_months', '—')),
                r.get('period', '—'),
            ])
        story.append(make_table(br_table, col_widths=br_cw))
    else:
        story.append(Paragraph('No burn & runway data available.', body))
    story.append(Spacer(1, 0.3 * cm))

    # ─── 10. SAAS METRICS ────────────────────────────────────────────
    story.append(Paragraph('9. SaaS Metrics', section_h))
    story.append(add_hr())

    saas_data = data.get('saas_metrics', [])
    if saas_data:
        saas_cw = [3.5 * cm, 2 * cm, 2 * cm, 2 * cm, 2 * cm, 2 * cm, 2 * cm, 1.5 * cm]
        saas_table = [['Company', 'MRR (Cr)', 'ARR (Cr)', 'Churn %',
                        'NRR %', 'CAC (Rs.)', 'LTV (Rs.)', 'LTV/CAC']]
        for r in saas_data:
            saas_table.append([
                r.get('company', '—')[:25],
                _fmt_cr(r.get('mrr')),
                _fmt_cr(r.get('arr')),
                _fmt_pct(r.get('churn_rate')),
                _fmt_pct(r.get('nrr')),
                _fmt_num(r.get('cac')),
                _fmt_num(r.get('ltv')),
                _fmt_num(r.get('ltv_cac_ratio')),
            ])
        story.append(make_table(saas_table, col_widths=saas_cw))
    else:
        story.append(Paragraph('No SaaS metrics data available.', body))
    story.append(PageBreak())

    # ─── 11. KPI DASHBOARD (Company Matrix) ──────────────────────────
    story.append(Paragraph('10. KPI Dashboard', section_h))
    story.append(add_hr())
    story.append(Paragraph(
        'Key performance indicators per company. Values extracted semantically via Gemini AI.',
        small
    ))
    story.append(Spacer(1, 0.2 * cm))

    kpi_matrix = data.get('kpi_matrix', [])
    if kpi_matrix:
        km_cw = [3.2 * cm, 1.5 * cm, 1.5 * cm, 1.3 * cm, 1.3 * cm, 1.3 * cm,
                  1.2 * cm, 1.3 * cm, 1.2 * cm, 1.2 * cm, 1.5 * cm, 1.5 * cm]
        km_table = [['Company', 'GMV (Cr)', 'REV (Cr)', 'Gross M%', 'EBITDA%',
                      'Orders', 'AOV', 'Returns%', 'CAC (Rs.)', 'Repeat%',
                      'Cost (Cr)', 'FV (Cr)']]
        for r in kpi_matrix:
            km_table.append([
                r.get('company', '—')[:22],
                _fmt_cr(r.get('gmv')),
                _fmt_cr(r.get('revenue')),
                _fmt_pct(r.get('gross_m')),
                _fmt_pct(r.get('ebitda')),
                _fmt_num(r.get('orders')) if r.get('orders') is not None else '—',
                _fmt_num(r.get('aov')) if r.get('aov') is not None else '—',
                _fmt_pct(r.get('returns')),
                _fmt_num(r.get('cac')) if r.get('cac') is not None else '—',
                _fmt_pct(r.get('repeat')),
                _fmt_cr(r.get('cost')),
                _fmt_cr(r.get('fv')),
            ])
        story.append(make_table(km_table, col_widths=km_cw, font_size=6))
    else:
        story.append(Paragraph('No KPI matrix data available.', body))
    story.append(PageBreak())

    # ─── 12. QUOTED VS UNQUOTED ──────────────────────────────────────
    story.append(Paragraph('11. Quoted vs Unquoted Breakdown', section_h))
    story.append(add_hr())

    quoted = data.get('quoted_companies', [])
    unquoted = data.get('unquoted_companies', [])
    qu_cw = [0.7 * cm, 4 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.3 * cm]

    if quoted:
        story.append(Paragraph('Quoted (Listed) Companies', subsection_h))
        q_table = [['#', 'Company', 'Sector', 'Exchange', 'Cost (Cr)', 'Fair Value (Cr)', 'IPEV Level']]
        for i, r in enumerate(quoted, 1):
            q_table.append([
                str(i), r.get('name', '')[:28], r.get('sector', '—'),
                r.get('exchange', '—'), _fmt_cr(r.get('cost')),
                _fmt_cr(r.get('fair_value')), str(r.get('ipev_level', '—')),
            ])
        story.append(make_table(q_table, col_widths=qu_cw))
        story.append(Spacer(1, 0.3 * cm))

    if unquoted:
        story.append(Paragraph('Unquoted (Unlisted) Companies', subsection_h))
        uq_table = [['#', 'Company', 'Sector', 'Exchange', 'Cost (Cr)', 'Fair Value (Cr)', 'IPEV Level']]
        for i, r in enumerate(unquoted, 1):
            uq_table.append([
                str(i), r.get('name', '')[:28], r.get('sector', '—'),
                r.get('exchange', '—'), _fmt_cr(r.get('cost')),
                _fmt_cr(r.get('fair_value')), str(r.get('ipev_level', '—')),
            ])
        story.append(make_table(uq_table, col_widths=qu_cw))

    if not quoted and not unquoted:
        story.append(Paragraph('No quoted/unquoted classification data available.', body))

    qu_summary = data.get('qu_summary', {})
    if qu_summary:
        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph(
            f'Total: {qu_summary.get("total", 0)} companies | '
            f'Quoted: {qu_summary.get("quoted_count", 0)} (Cost: {_fmt_cr(qu_summary.get("quoted_cost"))}) | '
            f'Unquoted: {qu_summary.get("unquoted_count", 0)} (Cost: {_fmt_cr(qu_summary.get("unquoted_cost"))})',
            ParagraphStyle('qu_sum', parent=body, fontName='Helvetica-Bold', fontSize=7)
        ))
    story.append(PageBreak())

    # ─── 13. INVESTMENTS SUMMARY ─────────────────────────────────────
    story.append(Paragraph('12. Investments Summary', section_h))
    story.append(add_hr())

    investments_list = data.get('investments_list', [])
    if investments_list:
        inv_cw = [0.6 * cm, 3 * cm, 2 * cm, 2 * cm, 1.8 * cm, 2 * cm, 1.8 * cm, 2 * cm, 1.8 * cm]
        inv_table = [['#', 'Company', 'Scheme', 'Sector', 'Stage', 'Invested (Cr)',
                       'Ownership %', 'Status', 'Inv. Date']]
        for i, r in enumerate(investments_list, 1):
            inv_table.append([
                str(i),
                r.get('company', '')[:22],
                r.get('scheme', '')[:15],
                r.get('sector', '—')[:12],
                r.get('stage', '—')[:10],
                _fmt_cr(r.get('total_invested')),
                _fmt_pct(r.get('ownership_pct')),
                r.get('status', '—'),
                _fmt_date(r.get('investment_date')),
            ])
        story.append(make_table(inv_table, col_widths=inv_cw, font_size=6))
    else:
        story.append(Paragraph('No investment records found.', body))
    story.append(Spacer(1, 0.3 * cm))

    # ─── 14. VALUATION SUMMARY (IPEV) ────────────────────────────────
    story.append(Paragraph('13. Valuation Summary (IPEV)', section_h))
    story.append(add_hr())

    valuations = data.get('valuations', [])
    if valuations:
        val_cw = [0.6 * cm, 3.2 * cm, 2 * cm, 2.3 * cm, 2.3 * cm, 1.5 * cm, 2.5 * cm, 2.1 * cm]
        val_table = [['#', 'Company', 'Sector', 'Invested (Cr)', 'Fair Value (Cr)',
                       'MOIC', 'Methodology', 'Val. Date']]
        for i, v in enumerate(valuations, 1):
            val_table.append([
                str(i),
                v.get('company', '')[:22],
                v.get('sector', '—')[:12],
                _fmt_cr(v.get('invested')),
                _fmt_cr(v.get('fair_value')),
                _fmt_num(v.get('moic')),
                v.get('methodology', '—'),
                v.get('date', ''),
            ])
        story.append(make_table(val_table, col_widths=val_cw, font_size=6))
        total_inv = sum(v.get('invested', 0) or 0 for v in valuations)
        total_fv = sum(v.get('fair_value', 0) or 0 for v in valuations)
        story.append(Paragraph(
            f'Total Invested: {_fmt_cr(total_inv)} | Total FV: {_fmt_cr(total_fv)} | '
            f'MOIC: {total_fv / total_inv:.2f}x' if total_inv > 0 else '',
            ParagraphStyle('val_sum', parent=body, fontName='Helvetica-Bold', fontSize=7)
        ))
    else:
        story.append(Paragraph('No valuation records found.', body))
    story.append(PageBreak())

    # ─── 15. NAV & UNIT VALUE ────────────────────────────────────────
    story.append(Paragraph('14. NAV & Unit Value', section_h))
    story.append(add_hr())

    nav_records = data.get('nav_records', [])
    if nav_records:
        nav_cw = [2.5 * cm, 2.8 * cm, 2.3 * cm, 2.8 * cm, 2.5 * cm, 3.6 * cm]
        nav_table = [['Date', 'Total NAV (Cr)', 'NAV / Unit', 'Units Outstanding',
                       'Mgmt Fee (Cr)', 'Scheme']]
        for n in nav_records[:24]:
            nav_table.append([
                n['date'], _fmt_cr(n['total_nav']),
                _fmt_num(n['nav_per_unit']),
                _fmt_num(n['total_units']),
                _fmt_cr(n['mgmt_fee']),
                n.get('scheme', '—')[:25],
            ])
        story.append(make_table(nav_table, col_widths=nav_cw))
        if len(nav_records) >= 2:
            first_nav = nav_records[-1]['total_nav']
            last_nav = nav_records[0]['total_nav']
            if first_nav and last_nav and first_nav > 0:
                change = ((last_nav - first_nav) / first_nav) * 100
                direction = 'increased' if change > 0 else 'decreased'
                story.append(Paragraph(
                    f'NAV has {direction} by {abs(change):.1f}% over the period '
                    f'from {_fmt_cr(first_nav)} to {_fmt_cr(last_nav)}.',
                    body
                ))
    else:
        story.append(Paragraph('No NAV records found.', body))
    story.append(Spacer(1, 0.3 * cm))

    # ─── 16. CAPITAL CALLS ───────────────────────────────────────────
    story.append(Paragraph('15. Capital Calls', section_h))
    story.append(add_hr())

    capital_calls = data.get('capital_calls', [])
    if capital_calls:
        cc_cw = [2 * cm, 3 * cm, 3.5 * cm, 5 * cm, 3 * cm]
        cc_table = [['Call #', 'Call Date', 'Amount (Cr)', 'Purpose', 'Status']]
        for c in capital_calls:
            cc_table.append([
                str(c.get('call_number', '')),
                c.get('date', '—'),
                _fmt_cr(c.get('amount')),
                c.get('purpose', '—')[:40],
                c.get('status', '—'),
            ])
        story.append(make_table(cc_table, col_widths=cc_cw))
    else:
        story.append(Paragraph('No capital call records found.', body))
    story.append(Spacer(1, 0.3 * cm))

    # ─── 17. DISTRIBUTIONS ───────────────────────────────────────────
    story.append(Paragraph('16. Distributions', section_h))
    story.append(add_hr())

    distributions = data.get('distributions', [])
    if distributions:
        dist_cw = [4 * cm, 6 * cm, 6.5 * cm]
        dist_table = [['Date', 'Amount (Cr)', 'Type']]
        for d in distributions:
            dist_table.append([
                d.get('date', '—'),
                _fmt_cr(d.get('amount')),
                d.get('type', '—'),
            ])
        story.append(make_table(dist_table, col_widths=dist_cw))
    else:
        story.append(Paragraph('No distribution records found.', body))
    story.append(PageBreak())

    # ─── 18. LP CAPITAL ACCOUNTS ─────────────────────────────────────
    story.append(Paragraph('17. LP Capital Accounts', section_h))
    story.append(add_hr())

    lp_accounts = data.get('lp_accounts', [])
    if lp_accounts:
        lp_cw = [3.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 3 * cm]
        lp_table = [['Investor', 'Committed (Cr)', 'Called (Cr)', 'Distributed (Cr)',
                      'Net Balance (Cr)', 'DPI']]
        for lp in lp_accounts:
            lp_table.append([
                lp.get('investor', '')[:25],
                _fmt_cr(lp.get('committed')),
                _fmt_cr(lp.get('called')),
                _fmt_cr(lp.get('distributed')),
                _fmt_cr(lp.get('net_balance')),
                _fmt_num(lp.get('dpi')),
            ])
        story.append(make_table(lp_table, col_widths=lp_cw))
    else:
        story.append(Paragraph('No LP capital account records found.', body))
    story.append(Spacer(1, 0.3 * cm))

    # ─── 19. FUND LEDGER ─────────────────────────────────────────────
    story.append(Paragraph('18. Fund Ledger', section_h))
    story.append(add_hr())
    story.append(Paragraph('Recent fund ledger entries (journal entries).', small))
    story.append(Spacer(1, 0.2 * cm))

    ledger_entries = data.get('ledger_entries', [])
    if ledger_entries:
        le_cw = [1.8 * cm, 2.2 * cm, 3 * cm, 3 * cm, 3 * cm, 2 * cm, 2 * cm]
        le_table = [['JE #', 'Date', 'Description', 'Debit Account', 'Credit Account',
                      'Amount (Cr)', 'Ref Type']]
        for e in ledger_entries[:40]:
            le_table.append([
                e.get('je_number', '—')[:10],
                e.get('date', '—'),
                e.get('description', '—')[:25],
                e.get('debit_account', '—')[:20],
                e.get('credit_account', '—')[:20],
                _fmt_cr(e.get('amount')),
                e.get('reference_type', '—'),
            ])
        story.append(make_table(le_table, col_widths=le_cw, font_size=6))
    else:
        story.append(Paragraph('No fund ledger entries found.', body))
    story.append(PageBreak())

    # ─── 20. TRIAL BALANCE ───────────────────────────────────────────
    story.append(Paragraph(f'19. Trial Balance Snapshot — {report_date_str}', section_h))
    story.append(add_hr())

    trial_balance = data.get('trial_balance', {})
    tb_accounts = trial_balance.get('accounts', [])
    if tb_accounts:
        tb_cw = [1.8 * cm, 4 * cm, 2.2 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2 * cm]
        tb_table = [['Code', 'Account Name', 'Type', 'Debit Total (Cr)',
                      'Credit Total (Cr)', 'Net Balance (Cr)', 'Side']]
        for a in tb_accounts:
            tb_table.append([
                a.get('account_code', '—'),
                a.get('account_name', '—')[:28],
                a.get('account_type', '—'),
                _fmt_cr(a.get('debit_total')),
                _fmt_cr(a.get('credit_total')),
                _fmt_cr(a.get('net_balance')),
                a.get('net_balance_side', '—'),
            ])
        story.append(make_table(tb_table, col_widths=tb_cw, font_size=6))
        story.append(Spacer(1, 0.2 * cm))
        is_balanced = trial_balance.get('is_balanced', False)
        story.append(Paragraph(
            f'Total Debits: {_fmt_cr(trial_balance.get("total_debits"))} | '
            f'Total Credits: {_fmt_cr(trial_balance.get("total_credits"))} | '
            f'Balanced: {"Yes" if is_balanced else "No (variance: " + _fmt_cr(trial_balance.get("variance")) + ")"}',
            ParagraphStyle('tb_sum', parent=body, fontName='Helvetica-Bold', fontSize=7)
        ))
    else:
        story.append(Paragraph('No trial balance data available. Ensure fund ledger entries exist.', body))
    story.append(Spacer(1, 0.3 * cm))

    # ─── 21. INVESTOR SUMMARY (SaaS / Sector) ────────────────────────
    story.append(Paragraph('20. Investor Summary (SaaS / Sector)', section_h))
    story.append(add_hr())

    investors = data.get('investors', [])
    if investors:
        is_cw = [3.5 * cm, 2 * cm, 3 * cm, 3 * cm, 3 * cm, 2 * cm]
        is_table = [['Investor', 'Type', 'Commitment (Cr)', 'Drawn Down (Cr)',
                      'Remaining (Cr)', 'Status']]
        for inv in investors:
            is_table.append([
                inv.get('name', '')[:25],
                inv.get('type', '—'),
                _fmt_cr(inv.get('commitment')),
                _fmt_cr(inv.get('drawn')),
                _fmt_cr(inv.get('remaining')),
                inv.get('status', 'Active'),
            ])
        story.append(make_table(is_table, col_widths=is_cw))
        total_commitment = sum(inv.get('commitment', 0) or 0 for inv in investors)
        total_drawn = sum(inv.get('drawn', 0) or 0 for inv in investors)
        if total_commitment > 0:
            story.append(Paragraph(
                f'Total Commitment: {_fmt_cr(total_commitment)} | Drawn: {_fmt_cr(total_drawn)} | '
                f'Deployment: {total_drawn / total_commitment * 100:.1f}%',
                ParagraphStyle('inv_sum', parent=body, fontName='Helvetica-Bold', fontSize=7)
            ))
    else:
        story.append(Paragraph('No investor records found.', body))
    story.append(Spacer(1, 0.3 * cm))

    # Sector breakdown
    sector_breakdown = data.get('sector_breakdown', [])
    if sector_breakdown:
        story.append(Paragraph('Sector-wise Portfolio Breakdown', subsection_h))
        sec_cw = [4 * cm, 2 * cm, 3.5 * cm, 3.5 * cm, 3.5 * cm]
        sec_table = [['Sector', '# Companies', 'Invested (Cr)', 'Fair Value (Cr)', 'Avg MOIC']]
        for s in sector_breakdown:
            sec_table.append([
                s.get('sector', '—'),
                str(s.get('count', 0)),
                _fmt_cr(s.get('invested')),
                _fmt_cr(s.get('fair_value')),
                _fmt_num(s.get('avg_moic')),
            ])
        story.append(make_table(sec_table, col_widths=sec_cw))
    story.append(PageBreak())

    # ─── 22. WATERFALL & CARRY SCHEDULE ──────────────────────────────
    story.append(Paragraph('21. Waterfall & Carry Schedule', section_h))
    story.append(add_hr())

    carry_records = data.get('carry_records', [])
    if carry_records:
        carry_cw = [3.5 * cm, 2.5 * cm, 3 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm]
        carry_table = [['Scheme', 'Date', 'Carry Base (Cr)', 'Carry Gross (Cr)',
                         'Carry Net (Cr)', 'GP Clawback (Cr)']]
        for c in carry_records:
            carry_table.append([
                c.get('scheme', '')[:25],
                c.get('date', ''),
                _fmt_cr(c.get('carry_base')),
                _fmt_cr(c.get('carry_gross')),
                _fmt_cr(c.get('carry_net')),
                _fmt_cr(c.get('clawback')),
            ])
        story.append(make_table(carry_table, col_widths=carry_cw))
        story.append(Spacer(1, 0.3 * cm))

    # Waterfall structure
    story.append(Paragraph('Standard AIF Waterfall Distribution', subsection_h))
    wf_data = [
        ['Tier', 'Description', 'Rate'],
        ['Return of Capital', 'Return 100% of contributed capital to LPs', '100%'],
        ['Preferred Return', f'Hurdle rate: {_fmt_pct(data.get("hurdle_rate"))}',
         _fmt_pct(data.get('hurdle_rate'))],
        ['GP Catch-up', 'GP receives accelerated carry until parity',
         f'{_fmt_pct(data.get("carry_pct"))} of catch-up'],
        ['Carried Interest', f'GP carry: {_fmt_pct(data.get("carry_pct"))} above hurdle',
         _fmt_pct(data.get('carry_pct'))],
    ]
    story.append(make_table(wf_data, col_widths=[4 * cm, 8.5 * cm, 4 * cm]))

    if not carry_records:
        story.append(Spacer(1, 0.2 * cm))
        story.append(Paragraph('No carried interest records found.', body))
    story.append(Spacer(1, 0.3 * cm))

    # ─── 23. ANOMALY ALERTS & RISK FLAGS ─────────────────────────────
    story.append(Paragraph('22. Anomaly Alerts & Risk Flags', section_h))
    story.append(add_hr())

    anomalies = data.get('anomalies', [])
    if anomalies:
        an_cw = [3 * cm, 2.5 * cm, 2 * cm, 6 * cm, 3 * cm]
        an_table = [['Company', 'Type', 'Severity', 'Description', 'Detected']]
        for a in anomalies:
            an_table.append([
                a.get('company', ''),
                a.get('type', ''),
                a.get('severity', ''),
                a.get('description', '')[:50],
                a.get('detected', ''),
            ])
        story.append(make_table(an_table, col_widths=an_cw))
    else:
        story.append(Paragraph(
            'No active anomaly alerts. All portfolio companies are within expected variance thresholds.',
            body
        ))
    story.append(PageBreak())

    # ─── 24. DISCLAIMER ──────────────────────────────────────────────
    story.append(Paragraph('23. Disclaimer & Notes', section_h))
    story.append(add_hr())
    story.append(Spacer(1, 0.2 * cm))

    disclaimers = [
        'This Comprehensive MIS Report has been generated automatically by TrackFundAI based on '
        'fund data uploaded by the fund manager. All financial figures are as reported in the '
        'uploaded MIS files and have not been independently audited.',
        'The valuations are based on IPEV guidelines. Fair values are indicative and subject to '
        'change based on market conditions and auditor review.',
        'Past performance is not indicative of future results. MOIC, IRR, DPI, TVPI are calculated '
        'based on available data and may differ from final audited figures.',
        'This report is CONFIDENTIAL and intended solely for authorised fund managers, LPs, and '
        'their designated advisors. Unauthorised distribution is prohibited.',
        'All amounts are in Indian Rupees (INR) expressed in Crores (Cr) unless otherwise stated. '
        '1 Cr = 10,000,000 INR.',
        'Budget vs Actual variances: (Actual - Budget). For revenue, positive variance is favorable. '
        'For costs, negative variance (under-spend) is favorable.',
        'The fund is registered with SEBI under the Alternative Investment Funds Regulations, 2012.',
    ]
    for i, d in enumerate(disclaimers):
        story.append(Paragraph(f'{i + 1}. {d}', ParagraphStyle(
            f'disc_{i}', parent=body, fontSize=7, leading=10,
            spaceBefore=4, spaceAfter=2, textColor=_DARK_GREY
        )))

    story.append(Spacer(1, 0.8 * cm))
    story.append(HRFlowable(width='100%', thickness=1, color=_DARK_BLUE))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        f'End of Report — Generated on {report_date_str} by TrackFundAI',
        ParagraphStyle('end', parent=small, alignment=TA_CENTER, fontName='Helvetica-Bold')
    ))

    # Build PDF
    fund_name = fund.name
    rdate = report_date_str

    def on_page(canvas, doc):
        _page_header_footer(canvas, doc, fund_name, rdate)

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    pdf_bytes = buf.getvalue()

    report_summary['total_pages'] = doc.page
    report_summary['sections'] = _build_screen_sections(data)
    report_summary['generated_at'] = timezone.now().isoformat()

    return pdf_bytes, report_summary


# ── Data Collection ─────────────────────────────────────────────────────

def _collect_all_data(fund, org):
    """Collect all data needed for the comprehensive MIS report."""
    from investments.models import PortfolioCompany, Investment, Valuation, PortfolioKPI, KPIDefinition
    from accounting.models import NAVRecord, CarriedInterest, FundLedger
    from lp.models import Investor, Commitment, CapitalCall, Distribution, LPCapitalAccount
    from mis_consolidation.models import BudgetVsActual, ConsolidatedMIS, MISAnomalyAlert
    from funds.models import Scheme

    import calendar

    data = {}
    schemes = Scheme.objects.filter(fund=fund)
    data['scheme_names'] = [s.name for s in schemes]
    data['vintage_year'] = schemes.first().vintage_year if schemes.exists() and hasattr(schemes.first(), 'vintage_year') else None
    data['hurdle_rate'] = schemes.first().hurdle_rate_pct if schemes.exists() and hasattr(schemes.first(), 'hurdle_rate_pct') else None
    data['carry_pct'] = schemes.first().carry_pct if schemes.exists() and hasattr(schemes.first(), 'carry_pct') else None

    # Companies
    companies = PortfolioCompany.objects.filter(organization=org, is_active=True)
    data['company_count'] = companies.count()

    # Investments
    investments = Investment.objects.filter(
        scheme__fund=fund, status__in=['active', 'partially_exited']
    ).select_related('portfolio_company', 'scheme')

    total_invested = sum(float(i.total_invested or 0) for i in investments)
    data['total_invested'] = total_invested

    # ── Investments list (for Investments Summary table) ──
    investments_list = []
    for inv in investments:
        investments_list.append({
            'company': inv.company_name[:30],
            'scheme': inv.scheme.name if inv.scheme else '—',
            'sector': inv.sector or '—',
            'stage': getattr(inv, 'stage', '—') or '—',
            'total_invested': float(inv.total_invested or 0),
            'ownership_pct': float(inv.ownership_pct) if hasattr(inv, 'ownership_pct') and inv.ownership_pct else None,
            'status': inv.status,
            'investment_date': str(inv.investment_date) if hasattr(inv, 'investment_date') and inv.investment_date else '—',
        })
    data['investments_list'] = investments_list

    # Latest valuations per investment
    valuations = []
    total_fv = 0
    for inv in investments:
        latest_val = inv.valuations.filter(status='approved').order_by('-valuation_date').first()
        if not latest_val:
            latest_val = inv.valuations.order_by('-valuation_date').first()
        fv = float(latest_val.fair_value_of_holding) if latest_val and latest_val.fair_value_of_holding else 0
        total_fv += fv
        invested = float(inv.total_invested or 0)
        moic = fv / invested if invested > 0 else 0
        valuations.append({
            'company': inv.company_name[:30],
            'sector': inv.sector or '—',
            'invested': invested,
            'fair_value': fv,
            'moic': round(moic, 2),
            'methodology': latest_val.methodology if latest_val else '—',
            'date': str(latest_val.valuation_date) if latest_val else '—',
        })
    data['valuations'] = valuations
    data['total_fv'] = total_fv
    data['aggregate_moic'] = round(total_fv / total_invested, 2) if total_invested > 0 else 0

    # NAV records
    nav_records = NAVRecord.objects.filter(
        scheme__fund=fund
    ).select_related('scheme').order_by('-nav_date')[:24]

    data['nav_records'] = [{
        'date': str(n.nav_date),
        'total_nav': float(n.total_nav),
        'nav_per_unit': float(n.nav_per_unit),
        'total_units': float(n.total_units_outstanding),
        'mgmt_fee': float(n.management_fee_payable),
        'scheme': n.scheme.name if n.scheme else '—',
    } for n in nav_records]

    data['latest_aum'] = float(nav_records[0].total_nav) if nav_records else None
    data['nav_per_unit'] = float(nav_records[0].nav_per_unit) if nav_records else None

    # Carried Interest
    carry_records = CarriedInterest.objects.filter(
        scheme__fund=fund
    ).select_related('scheme').order_by('-calculation_date')[:12]
    data['carry_records'] = [{
        'scheme': c.scheme.name if c.scheme else '—',
        'date': str(c.calculation_date),
        'carry_base': float(c.carry_base),
        'carry_gross': float(c.carry_amount_gross),
        'carry_net': float(c.carry_amount_net),
        'clawback': float(c.gp_clawback_provision),
    } for c in carry_records]

    # ── BudgetVsActual — build consolidated P&L (dashboard-style) ────
    line_item_display = dict(BudgetVsActual._meta.get_field('line_item').choices)

    bva_qs = BudgetVsActual.objects.filter(
        portfolio_company__organization=org, fund=fund
    ).select_related('portfolio_company').order_by(
        'portfolio_company__name', '-period_year', '-period_month', 'line_item'
    )

    # Group BvA by company → get latest period per company → extract rev/ebitda/pat
    company_bva = defaultdict(list)
    for r in bva_qs:
        company_bva[r.portfolio_company.name].append(r)

    pl_consolidated = []
    bva_summary = []
    agg_revenue = Decimal('0')
    agg_ebitda = Decimal('0')
    agg_pat = Decimal('0')

    for co_name, records in company_bva.items():
        # Find latest period
        latest_year = max(r.period_year for r in records)
        latest_month_records = [r for r in records if r.period_year == latest_year]
        months = [r.period_month for r in latest_month_records if r.period_month]
        latest_month = max(months) if months else None
        if latest_month:
            period_records = [r for r in latest_month_records if r.period_month == latest_month]
        else:
            period_records = latest_month_records

        rev = None
        ebitda = None
        pat = None
        for r in period_records:
            if r.line_item in ('revenue', 'total_revenue') and r.actual_inr:
                rev = float(r.actual_inr)
            elif r.line_item == 'ebitda' and r.actual_inr:
                ebitda = float(r.actual_inr)
            elif r.line_item == 'pat' and r.actual_inr:
                pat = float(r.actual_inr)

        ebitda_pct = None
        if rev and ebitda and rev != 0:
            ebitda_pct = ebitda / rev * 100

        if latest_month:
            period_label = f'{calendar.month_abbr[latest_month]}-{latest_year}'
        else:
            period_label = str(latest_year)

        pl_consolidated.append({
            'company': co_name,
            'revenue': rev,
            'ebitda': ebitda,
            'pat': pat,
            'ebitda_pct': ebitda_pct,
            'period': period_label,
        })

        if rev:
            agg_revenue += Decimal(str(rev))
        if ebitda:
            agg_ebitda += Decimal(str(ebitda))
        if pat:
            agg_pat += Decimal(str(pat))

        # BvA detail records (for variance table)
        for r in records:
            if r.budget_inr is not None and r.actual_inr is not None:
                bva_summary.append({
                    'company': co_name,
                    'line_item': line_item_display.get(r.line_item, r.line_item),
                    'budget': float(r.budget_inr),
                    'actual': float(r.actual_inr),
                    'variance': float(r.actual_inr - r.budget_inr),
                    'variance_pct': float(r.variance_pct) if r.variance_pct else None,
                    'is_favorable': r.is_favorable,
                })

    # ── Fallback: if no BvA P&L, synthesize from PortfolioKPI ────────
    if not pl_consolidated:
        KPI_PL_SLUGS = {
            'revenue': ['revenue', 'rev', 'net-sales', 'revcr', 'rev-cr', 'revenue-rs-cr', 'revenuecr'],
            'ebitda': ['ebitda', 'ebitda-cr', 'ebitdacr', 'ebitda-margin'],
            'pat': ['pat', 'net-profit', 'net-income', 'profit-after-tax'],
        }
        slug_to_pl = {}
        for pl_key, slugs in KPI_PL_SLUGS.items():
            for s in slugs:
                slug_to_pl[s] = pl_key

        kpi_qs = PortfolioKPI.objects.filter(
            investment__scheme__fund=fund
        ).select_related('kpi_definition', 'investment__portfolio_company').order_by(
            'investment__portfolio_company__name', '-period'
        )

        co_kpi_pl = defaultdict(lambda: {'revenue': None, 'ebitda': None, 'pat': None, 'period': None})
        for kpi in kpi_qs:
            slug = kpi.kpi_definition.slug.lower()
            pl_key = None
            for pattern, pk in slug_to_pl.items():
                if pattern in slug:
                    pl_key = pk
                    break
            if not pl_key:
                continue
            co_name = kpi.investment.portfolio_company.name if kpi.investment.portfolio_company else kpi.investment.company_name
            if co_kpi_pl[co_name][pl_key] is None:
                co_kpi_pl[co_name][pl_key] = float(kpi.value) if kpi.value else None
                if co_kpi_pl[co_name]['period'] is None:
                    if kpi.period:
                        co_kpi_pl[co_name]['period'] = f'{calendar.month_abbr[kpi.period.month]}-{kpi.period.year}'
                    else:
                        co_kpi_pl[co_name]['period'] = '—'

        for co_name, vals in co_kpi_pl.items():
            rev = vals.get('revenue')
            ebitda_raw = vals.get('ebitda')
            pat = vals.get('pat')

            # If ebitda looks like a margin (value < 1), treat as percentage
            # and compute absolute EBITDA from revenue × margin
            ebitda = ebitda_raw
            ebitda_pct = None
            if ebitda_raw is not None and abs(ebitda_raw) < 1:
                # It's a margin, not an absolute value
                ebitda_pct = ebitda_raw * 100
                if rev and rev > 0:
                    ebitda = rev * ebitda_raw  # absolute EBITDA
                else:
                    ebitda = None  # can't compute absolute without revenue
            elif rev and ebitda and rev != 0:
                ebitda_pct = ebitda / rev * 100

            pl_consolidated.append({
                'company': co_name,
                'revenue': rev,
                'ebitda': round(ebitda, 2) if ebitda is not None else None,
                'pat': pat,
                'ebitda_pct': round(ebitda_pct, 1) if ebitda_pct is not None else None,
                'period': vals.get('period', '—'),
            })
            if rev:
                agg_revenue += Decimal(str(rev))
            if ebitda:
                agg_ebitda += Decimal(str(round(ebitda, 2)))
            if pat:
                agg_pat += Decimal(str(pat))

    # Sort by revenue descending
    pl_consolidated.sort(key=lambda x: x.get('revenue') or 0, reverse=True)
    data['pl_consolidated'] = pl_consolidated

    # Fallback: if no BvA detail, build from ConsolidatedMIS actuals vs budgets
    if not bva_summary:
        cons_bva_qs = ConsolidatedMIS.objects.filter(
            fund=fund, organization=org
        ).order_by('-period_year', '-period_month', 'line_item')

        # Get the latest period
        latest_cons = cons_bva_qs.first()
        if latest_cons:
            latest_yr = latest_cons.period_year
            latest_mo = latest_cons.period_month
            period_cons = cons_bva_qs.filter(period_year=latest_yr, period_month=latest_mo)
            for c in period_cons:
                actual = float(c.total_actual_inr) if c.total_actual_inr else 0
                budget = float(c.total_budget_inr) if c.total_budget_inr else 0
                variance = actual - budget
                variance_pct = (variance / budget * 100) if budget != 0 else None
                is_fav = None
                if c.line_item in ('revenue', 'total_revenue', 'gross_profit', 'ebitda', 'ebit', 'pbt', 'pat', 'other_income'):
                    is_fav = variance >= 0
                elif c.line_item in ('cogs', 'total_opex', 'depreciation'):
                    is_fav = variance <= 0
                period_label = f'{calendar.month_abbr[latest_mo]}-{latest_yr}' if latest_mo else str(latest_yr)
                bva_summary.append({
                    'company': f'{fund.name} (Fund)',
                    'line_item': c.line_item.replace('_', ' ').title(),
                    'budget': budget,
                    'actual': actual,
                    'variance': variance,
                    'variance_pct': round(variance_pct, 1) if variance_pct is not None else None,
                    'is_favorable': is_fav,
                })

    data['bva_summary'] = bva_summary[:80]
    data['agg_revenue'] = float(agg_revenue) if agg_revenue else None
    data['agg_ebitda'] = float(agg_ebitda) if agg_ebitda else None
    data['agg_pat'] = float(agg_pat) if agg_pat else None

    # ── Consolidated Fund P&L (fund-level monthly rollup) ────────────
    consolidated_qs = ConsolidatedMIS.objects.filter(
        fund=fund, organization=org
    ).order_by('-period_year', '-period_month')

    fund_pl_map = defaultdict(lambda: {'revenue': None, 'ebitda': None, 'pat': None, 'company_count': 0})
    for c in consolidated_qs:
        key = f'{c.period_year}-{c.period_month or "Annual"}'
        if c.line_item in ('revenue', 'total_revenue') and fund_pl_map[key]['revenue'] is None:
            fund_pl_map[key]['revenue'] = float(c.total_actual_inr) if c.total_actual_inr else None
            fund_pl_map[key]['company_count'] = c.company_count or 0
        elif c.line_item == 'ebitda' and fund_pl_map[key]['ebitda'] is None:
            fund_pl_map[key]['ebitda'] = float(c.total_actual_inr) if c.total_actual_inr else None
        elif c.line_item == 'pat' and fund_pl_map[key]['pat'] is None:
            fund_pl_map[key]['pat'] = float(c.total_actual_inr) if c.total_actual_inr else None

    fund_pl = []
    for period_key in sorted(fund_pl_map.keys(), reverse=True)[:12]:
        vals = fund_pl_map[period_key]
        parts = period_key.split('-')
        if len(parts) == 2 and parts[1] != 'Annual':
            try:
                period_label = f'{calendar.month_abbr[int(parts[1])]}-{parts[0]}'
            except (ValueError, IndexError):
                period_label = period_key
        else:
            period_label = period_key
        rev = vals.get('revenue')
        ebitda = vals.get('ebitda')
        ebitda_pct = None
        if rev and ebitda and rev != 0:
            ebitda_pct = ebitda / rev * 100
        fund_pl.append({
            'period': period_label,
            'revenue': rev,
            'ebitda': ebitda,
            'pat': vals.get('pat'),
            'ebitda_pct': ebitda_pct,
            'company_count': vals.get('company_count', 0),
        })
    data['fund_pl'] = fund_pl

    # ── Balance Sheet (consolidated — one row per company) ───────────
    BS_ITEMS = {'total_assets', 'net_worth', 'total_debt', 'cash_and_equivalents'}

    bs_bva = BudgetVsActual.objects.filter(
        portfolio_company__organization=org, fund=fund,
        line_item__in=BS_ITEMS
    ).select_related('portfolio_company').order_by(
        'portfolio_company__name', '-period_year', '-period_month'
    )

    bs_co = defaultdict(dict)
    for r in bs_bva:
        co_name = r.portfolio_company.name
        if r.line_item not in bs_co[co_name]:
            bs_co[co_name][r.line_item] = {
                'value': float(r.actual_inr) if r.actual_inr else None,
                'period': f'{r.period_year}-{r.period_month or "Annual"}',
            }

    bs_consolidated = []
    for co_name, items in sorted(bs_co.items()):
        period = next((v['period'] for v in items.values() if v.get('period')), '—')
        parts = period.split('-')
        if len(parts) == 2 and parts[1] != 'Annual':
            try:
                period = f'{calendar.month_abbr[int(parts[1])]}-{parts[0]}'
            except (ValueError, IndexError):
                pass
        bs_consolidated.append({
            'company': co_name,
            'total_assets': items.get('total_assets', {}).get('value'),
            'net_worth': items.get('net_worth', {}).get('value'),
            'total_debt': items.get('total_debt', {}).get('value'),
            'cash': items.get('cash_and_equivalents', {}).get('value'),
            'period': period,
        })

    # Fallback: build fund-level Balance Sheet from NAVRecord if BvA BS is empty
    if not bs_consolidated:
        latest_nav = NAVRecord.objects.filter(
            scheme__fund=fund
        ).order_by('-nav_date').first()
        if latest_nav:
            nav_date_str = f'{calendar.month_abbr[latest_nav.nav_date.month]}-{latest_nav.nav_date.year}'
            total_assets = float(latest_nav.investments_at_fair_value or 0) + \
                           float(latest_nav.cash_and_equivalents or 0) + \
                           float(latest_nav.receivables or 0)
            total_liabilities = float(latest_nav.management_fee_payable or 0) + \
                                float(latest_nav.other_liabilities or 0)
            net_worth = total_assets - total_liabilities
            bs_consolidated.append({
                'company': f'{fund.name} (Fund-Level)',
                'total_assets': total_assets,
                'net_worth': net_worth,
                'total_debt': total_liabilities,
                'cash': float(latest_nav.cash_and_equivalents or 0),
                'period': nav_date_str,
            })
            # Also add a detailed breakdown as separate rows
            bs_consolidated.append({
                'company': '  Investments at Fair Value',
                'total_assets': float(latest_nav.investments_at_fair_value or 0),
                'net_worth': None,
                'total_debt': None,
                'cash': None,
                'period': nav_date_str,
            })
            bs_consolidated.append({
                'company': '  Receivables',
                'total_assets': float(latest_nav.receivables or 0),
                'net_worth': None,
                'total_debt': None,
                'cash': None,
                'period': nav_date_str,
            })
            bs_consolidated.append({
                'company': '  Mgmt Fee Payable',
                'total_assets': None,
                'net_worth': None,
                'total_debt': float(latest_nav.management_fee_payable or 0),
                'cash': None,
                'period': nav_date_str,
            })
            bs_consolidated.append({
                'company': '  Other Liabilities',
                'total_assets': None,
                'net_worth': None,
                'total_debt': float(latest_nav.other_liabilities or 0),
                'cash': None,
                'period': nav_date_str,
            })
            bs_consolidated.append({
                'company': '  Total NAV',
                'total_assets': float(latest_nav.total_nav or 0),
                'net_worth': float(latest_nav.total_nav or 0),
                'total_debt': None,
                'cash': None,
                'period': nav_date_str,
            })

    data['bs_consolidated'] = bs_consolidated

    # ── Cash Flow (consolidated — one row per company) ───────────────
    CF_ITEMS = {'cash_and_equivalents', 'finance_cost', 'capex', 'dividend'}

    cf_bva = BudgetVsActual.objects.filter(
        portfolio_company__organization=org, fund=fund,
        line_item__in=CF_ITEMS
    ).select_related('portfolio_company').order_by(
        'portfolio_company__name', '-period_year', '-period_month'
    )

    cf_co = defaultdict(dict)
    for r in cf_bva:
        co_name = r.portfolio_company.name
        if r.line_item not in cf_co[co_name]:
            cf_co[co_name][r.line_item] = {
                'value': float(r.actual_inr) if r.actual_inr else None,
                'period': f'{r.period_year}-{r.period_month or "Annual"}',
            }

    cf_consolidated = []
    for co_name, items in sorted(cf_co.items()):
        period = next((v['period'] for v in items.values() if v.get('period')), '—')
        parts = period.split('-')
        if len(parts) == 2 and parts[1] != 'Annual':
            try:
                period = f'{calendar.month_abbr[int(parts[1])]}-{parts[0]}'
            except (ValueError, IndexError):
                pass
        cf_consolidated.append({
            'company': co_name,
            'cash': items.get('cash_and_equivalents', {}).get('value'),
            'finance_cost': items.get('finance_cost', {}).get('value'),
            'capex': items.get('capex', {}).get('value'),
            'dividend': items.get('dividend', {}).get('value'),
            'period': period,
        })

    # Fallback: build fund-level Cash Flow from FundLedger if BvA CF is empty
    if not cf_consolidated:
        ledger_qs = FundLedger.objects.filter(
            scheme__fund=fund, is_reversed=False
        ).order_by('-entry_date')

        if ledger_qs.exists():
            # Group by reference_type and sum amounts
            from django.db.models import Sum
            cf_by_type = ledger_qs.values('reference_type').annotate(
                total=Sum('amount')
            ).order_by('reference_type')

            cf_type_totals = {}
            for row in cf_by_type:
                cf_type_totals[row['reference_type']] = float(row['total'] or 0)

            latest_entry = ledger_qs.first()
            cf_period = f'{calendar.month_abbr[latest_entry.entry_date.month]}-{latest_entry.entry_date.year}' if latest_entry else '—'

            capital_inflows = cf_type_totals.get('capital_call', 0)
            investment_outflows = cf_type_totals.get('investment', 0)
            distributions_out = cf_type_totals.get('distribution', 0)
            mgmt_fees = cf_type_totals.get('management_fee', 0)
            carry = cf_type_totals.get('carried_interest', 0)
            expenses = cf_type_totals.get('expense', 0)
            other = cf_type_totals.get('other', 0)

            # Operating: mgmt fees + expenses
            operating_cf = -(mgmt_fees + expenses)
            # Investing: investments made (outflow)
            investing_cf = -investment_outflows
            # Financing: capital calls (inflow) - distributions (outflow) - carry
            financing_cf = capital_inflows - distributions_out - carry

            net_cf = operating_cf + investing_cf + financing_cf

            # Get ending cash from latest NAVRecord
            latest_nav = NAVRecord.objects.filter(scheme__fund=fund).order_by('-nav_date').first()
            ending_cash = float(latest_nav.cash_and_equivalents or 0) if latest_nav else None

            data['cf_fund_level'] = True
            cf_consolidated = [
                {
                    'item': 'Capital Calls Received',
                    'amount': capital_inflows,
                    'category': 'Financing',
                },
                {
                    'item': 'Investments Made',
                    'amount': -investment_outflows,
                    'category': 'Investing',
                },
                {
                    'item': 'Distributions Paid',
                    'amount': -distributions_out,
                    'category': 'Financing',
                },
                {
                    'item': 'Management Fees',
                    'amount': -mgmt_fees,
                    'category': 'Operating',
                },
                {
                    'item': 'Carried Interest',
                    'amount': -carry,
                    'category': 'Financing',
                },
                {
                    'item': 'Other Expenses',
                    'amount': -(expenses + other),
                    'category': 'Operating',
                },
                {
                    'item': 'Net Cash Flow',
                    'amount': net_cf,
                    'category': 'Total',
                },
            ]
            if ending_cash is not None:
                cf_consolidated.append({
                    'item': 'Cash & Equivalents (Latest)',
                    'amount': ending_cash,
                    'category': 'Balance',
                })
            data['cf_period'] = cf_period

    data['cf_consolidated'] = cf_consolidated

    # ── Burn & Runway (from PortfolioKPI or CompanyFinancials) ────────
    burn_runway = []
    BURN_SLUGS = {
        'gross_burn': ['gross-burn', 'burn-rate', 'monthly-burn', 'gross-burn-rate'],
        'net_burn': ['net-burn', 'net-burn-rate'],
        'cash_balance': ['cash', 'cash-and-equivalents', 'cash-balance', 'cash-in-hand'],
        'runway_months': ['runway-months', 'runway', 'cash-runway'],
    }
    slug_to_burn = {}
    for bk, slugs in BURN_SLUGS.items():
        for s in slugs:
            slug_to_burn[s] = bk

    burn_kpis = PortfolioKPI.objects.filter(
        investment__scheme__fund=fund
    ).select_related('kpi_definition', 'investment__portfolio_company').order_by(
        'investment__portfolio_company__name', '-period'
    )

    co_burn = defaultdict(lambda: {'gross_burn': None, 'net_burn': None, 'cash_balance': None, 'runway_months': None, 'period': None})
    for kpi in burn_kpis:
        slug = kpi.kpi_definition.slug.lower()
        burn_key = None
        for pattern, bk in slug_to_burn.items():
            if pattern in slug:
                burn_key = bk
                break
        if not burn_key:
            continue
        co_name = kpi.investment.portfolio_company.name if kpi.investment.portfolio_company else kpi.investment.company_name
        if co_burn[co_name][burn_key] is None:
            co_burn[co_name][burn_key] = float(kpi.value) if kpi.value else None
            if co_burn[co_name]['period'] is None:
                co_burn[co_name]['period'] = str(kpi.period)

    for co_name, vals in sorted(co_burn.items()):
        if any(v is not None for k, v in vals.items() if k != 'period'):
            burn_runway.append({
                'company': co_name,
                'gross_burn': vals.get('gross_burn'),
                'net_burn': vals.get('net_burn'),
                'cash_balance': vals.get('cash_balance'),
                'runway_months': int(vals['runway_months']) if vals.get('runway_months') else None,
                'period': vals.get('period', '—'),
            })

    # Fallback: derive fund-level burn from ConsolidatedMIS if no KPI burn data
    if not burn_runway:
        cons_latest = ConsolidatedMIS.objects.filter(
            fund=fund, organization=org
        ).order_by('-period_year', '-period_month').first()

        if cons_latest:
            cons_period = ConsolidatedMIS.objects.filter(
                fund=fund, organization=org,
                period_year=cons_latest.period_year,
                period_month=cons_latest.period_month
            )
            total_opex = None
            ebitda_val = None
            revenue_val = None
            for c in cons_period:
                if c.line_item == 'total_opex' and c.total_actual_inr:
                    total_opex = float(c.total_actual_inr)
                elif c.line_item == 'ebitda' and c.total_actual_inr:
                    ebitda_val = float(c.total_actual_inr)
                elif c.line_item in ('revenue', 'total_revenue') and c.total_actual_inr:
                    revenue_val = float(c.total_actual_inr)

            # Gross burn = total_opex (monthly), Net burn = opex - revenue (if negative, company is profitable)
            gross_burn = total_opex
            net_burn = (total_opex - revenue_val) if total_opex and revenue_val else total_opex

            # Get cash from NAVRecord
            latest_nav = NAVRecord.objects.filter(scheme__fund=fund).order_by('-nav_date').first()
            cash_bal = float(latest_nav.cash_and_equivalents or 0) if latest_nav else None

            runway = None
            if net_burn and net_burn > 0 and cash_bal and cash_bal > 0:
                runway = int(cash_bal / net_burn)

            period_label = f'{calendar.month_abbr[cons_latest.period_month]}-{cons_latest.period_year}' if cons_latest.period_month else str(cons_latest.period_year)

            burn_runway.append({
                'company': f'{fund.name} (Fund-Level)',
                'gross_burn': gross_burn,
                'net_burn': net_burn if net_burn and net_burn > 0 else None,
                'cash_balance': cash_bal,
                'runway_months': runway,
                'period': period_label,
            })

    data['burn_runway'] = burn_runway

    # ── SaaS Metrics (from PortfolioKPI) ─────────────────────────────
    SAAS_SLUGS = {
        'mrr': ['mrr', 'monthly-recurring-revenue', 'monthly-revenue'],
        'arr': ['arr', 'annual-recurring-revenue', 'annual-revenue-run-rate'],
        'churn_rate': ['churn-rate', 'churn', 'revenue-churn', 'customer-churn'],
        'nrr': ['nrr', 'net-revenue-retention', 'net-dollar-retention', 'ndr'],
        'cac': ['cac', 'customer-acquisition-cost', 'blended-cac'],
        'ltv': ['ltv', 'clv', 'customer-ltv', 'lifetime-value', 'customer-lifetime-value'],
        'ltv_cac_ratio': ['ltv-cac', 'ltv-cac-ratio', 'ltv-cac-multiple'],
    }
    slug_to_saas = {}
    for sk, slugs in SAAS_SLUGS.items():
        for s in slugs:
            slug_to_saas[s] = sk

    saas_kpis = PortfolioKPI.objects.filter(
        investment__scheme__fund=fund
    ).select_related('kpi_definition', 'investment__portfolio_company').order_by(
        'investment__portfolio_company__name', '-period'
    )

    co_saas = defaultdict(lambda: {k: None for k in SAAS_SLUGS})
    for kpi in saas_kpis:
        slug = kpi.kpi_definition.slug.lower()
        saas_key = None
        for pattern, sk in slug_to_saas.items():
            if pattern in slug:
                saas_key = sk
                break
        if not saas_key:
            continue
        co_name = kpi.investment.portfolio_company.name if kpi.investment.portfolio_company else kpi.investment.company_name
        if co_saas[co_name][saas_key] is None:
            co_saas[co_name][saas_key] = float(kpi.value) if kpi.value else None

    saas_metrics = []
    for co_name, vals in sorted(co_saas.items()):
        if any(v is not None for v in vals.values()):
            saas_metrics.append({
                'company': co_name,
                **vals,
            })
    data['saas_metrics'] = saas_metrics

    # ── KPI Matrix (company × KPI columns — GMV, REV, Gross M%, etc.) ──
    _KPI_COL_SLUGS = {
        'gmv':      ['gmv', 'gmv-rs-cr', 'gmvcr'],
        'revenue':  ['rev', 'revenue', 'revenue-rs-cr', 'revenuecr'],
        'gross_m':  ['gross-m', 'gross-margin'],
        'ebitda':   ['ebitda', 'ebitda-margin'],
        'orders':   ['orders', 'order-book', 'order-book-rs-cr'],
        'aov':      ['aov'],
        'returns':  ['returns'],
        'cac':      ['cac'],
        'repeat':   ['repeat'],
    }
    _SLUG_TO_COL = {}
    for _col, _slugs in _KPI_COL_SLUGS.items():
        for _s in _slugs:
            _SLUG_TO_COL[_s] = _col

    # Build company data from investments
    company_data = {}
    for inv in investments:
        co_name = inv.company_name
        if co_name not in company_data:
            company_data[co_name] = {
                'inv_ids': [],
                'cost': float(inv.total_invested or 0),
                'sector': inv.sector or '—',
            }
        else:
            company_data[co_name]['cost'] += float(inv.total_invested or 0)
        company_data[co_name]['inv_ids'].append(inv.id)

    # Get FV per company
    for co_name, cd in company_data.items():
        total_fv_co = 0
        for inv_id in cd['inv_ids']:
            latest_v = Valuation.objects.filter(
                investment_id=inv_id, status='approved'
            ).order_by('-valuation_date').first()
            if not latest_v:
                latest_v = Valuation.objects.filter(
                    investment_id=inv_id
                ).order_by('-valuation_date').first()
            if latest_v and latest_v.fair_value_of_holding:
                total_fv_co += float(latest_v.fair_value_of_holding)
        cd['fv'] = total_fv_co

    # Get KPIs matching target slugs
    all_inv_ids = [inv.id for inv in investments]
    target_slugs = set()
    for slugs in _KPI_COL_SLUGS.values():
        target_slugs.update(slugs)

    kpi_qs = PortfolioKPI.objects.filter(
        investment_id__in=all_inv_ids,
        kpi_definition__slug__in=target_slugs
    ).select_related('kpi_definition', 'investment').order_by('-period')

    company_kpis = defaultdict(dict)
    for kpi in kpi_qs:
        co_name = kpi.investment.company_name
        slug = kpi.kpi_definition.slug.lower()
        col = _SLUG_TO_COL.get(slug)
        if col and col not in company_kpis[co_name]:
            company_kpis[co_name][col] = float(kpi.value) if kpi.value else None

    # Broader fuzzy matching
    all_kpis = PortfolioKPI.objects.filter(
        investment_id__in=all_inv_ids
    ).select_related('kpi_definition', 'investment').order_by('-period')

    for kpi in all_kpis:
        co_name = kpi.investment.company_name
        slug = kpi.kpi_definition.slug.lower()
        for col, patterns in _KPI_COL_SLUGS.items():
            if col not in company_kpis[co_name]:
                for p in patterns:
                    if p in slug:
                        company_kpis[co_name][col] = float(kpi.value) if kpi.value else None
                        break

    # Normalize percentages
    PCT_COLS = {'gross_m', 'ebitda', 'returns', 'repeat'}
    for co_name, kvals in company_kpis.items():
        for pc in PCT_COLS:
            v = kvals.get(pc)
            if v is not None and abs(v) < 1:
                kvals[pc] = round(v * 100, 2)

    kpi_matrix = []
    for co_name in sorted(company_data.keys()):
        cd = company_data[co_name]
        kvals = company_kpis.get(co_name, {})
        kpi_matrix.append({
            'company': co_name,
            'gmv': kvals.get('gmv'),
            'revenue': kvals.get('revenue'),
            'gross_m': kvals.get('gross_m'),
            'ebitda': kvals.get('ebitda'),
            'orders': kvals.get('orders'),
            'aov': kvals.get('aov'),
            'returns': kvals.get('returns'),
            'cac': kvals.get('cac'),
            'repeat': kvals.get('repeat'),
            'cost': cd.get('cost'),
            'fv': cd.get('fv'),
        })
    data['kpi_matrix'] = kpi_matrix

    # ── Quoted vs Unquoted ───────────────────────────────────────────
    quoted = []
    unquoted = []
    for inv in investments:
        co = inv.portfolio_company
        is_quoted = getattr(co, 'is_quoted', False)
        latest_v = inv.valuations.order_by('-valuation_date').first()
        ipev_level = latest_v.ipev_level if latest_v and hasattr(latest_v, 'ipev_level') else None
        entry = {
            'name': co.name,
            'sector': co.sector if hasattr(co, 'sector') and co.sector else '—',
            'exchange': getattr(co, 'exchange', '') or '',
            'cost': float(inv.total_invested or 0),
            'fair_value': float(latest_v.fair_value_of_holding) if latest_v and latest_v.fair_value_of_holding else 0,
            'ipev_level': ipev_level or '—',
        }
        if is_quoted or ipev_level == 1:
            quoted.append(entry)
        else:
            unquoted.append(entry)
    data['quoted_companies'] = quoted
    data['unquoted_companies'] = unquoted
    data['qu_summary'] = {
        'total': len(quoted) + len(unquoted),
        'quoted_count': len(quoted),
        'unquoted_count': len(unquoted),
        'quoted_cost': sum(q.get('cost', 0) for q in quoted),
        'unquoted_cost': sum(q.get('cost', 0) for q in unquoted),
    }

    # ── Investors ────────────────────────────────────────────────────
    investors_qs = Investor.objects.filter(organization=org)
    commitments = Commitment.objects.filter(scheme__fund=fund).select_related('investor')
    data['investor_count'] = investors_qs.count()

    investor_data = []
    for c in commitments:
        commitment_amt = float(c.commitment_amount or 0)
        investor_data.append({
            'name': c.investor.investor_name if c.investor else '—',
            'type': c.investor.investor_type if c.investor else '—',
            'commitment': commitment_amt,
            'drawn': 0,
            'remaining': commitment_amt,
            'status': c.commitment_status if hasattr(c, 'commitment_status') else 'Active',
        })
    data['investors'] = investor_data

    # ── Capital Calls ────────────────────────────────────────────────
    capital_calls = CapitalCall.objects.filter(
        scheme__fund=fund
    ).order_by('-call_date')[:30]
    data['capital_calls'] = [{
        'call_number': c.call_number,
        'date': str(c.call_date) if c.call_date else '—',
        'amount': float(c.total_call_amount or 0),
        'purpose': c.purpose if hasattr(c, 'purpose') else '—',
        'status': c.call_status,
    } for c in capital_calls]

    # ── Distributions ────────────────────────────────────────────────
    distributions = Distribution.objects.filter(
        scheme__fund=fund
    ).order_by('-distribution_date')[:30]
    data['distributions'] = [{
        'date': str(d.distribution_date) if d.distribution_date else '—',
        'amount': float(d.total_gross_amount or 0),
        'type': d.distribution_type or '—',
    } for d in distributions]

    # ── LP Capital Accounts ──────────────────────────────────────────
    lp_accounts = LPCapitalAccount.objects.filter(
        commitment__scheme__fund=fund
    ).select_related('commitment__investor')[:30]
    data['lp_accounts'] = [{
        'investor': lp.commitment.investor.investor_name if lp.commitment and lp.commitment.investor else '—',
        'committed': float(lp.committed_capital) if lp.committed_capital else 0,
        'called': float(lp.called_capital) if lp.called_capital else 0,
        'distributed': float(lp.distributed_capital) if lp.distributed_capital else 0,
        'net_balance': float((lp.called_capital or 0) - (lp.distributed_capital or 0)),
        'dpi': float(lp.dpi) if lp.dpi else 0,
    } for lp in lp_accounts]

    # ── Fund Ledger (recent entries) ─────────────────────────────────
    ledger_entries = []
    for scheme in schemes:
        entries = FundLedger.objects.filter(
            scheme=scheme, is_reversed=False
        ).select_related('debit_account', 'credit_account').order_by('-entry_date')[:30]
        for e in entries:
            ledger_entries.append({
                'je_number': e.journal_entry_number or '—',
                'date': str(e.entry_date) if e.entry_date else '—',
                'description': e.description or '—',
                'debit_account': e.debit_account.account_name if e.debit_account else '—',
                'credit_account': e.credit_account.account_name if e.credit_account else '—',
                'amount': float(e.amount or 0),
                'reference_type': e.reference_type or '—',
            })
    ledger_entries.sort(key=lambda x: x['date'], reverse=True)
    data['ledger_entries'] = ledger_entries[:40]

    # ── Trial Balance (for first scheme) ─────────────────────────────
    trial_balance = {}
    if schemes.exists():
        try:
            from accounting.trial_balance import generate_trial_balance
            tb = generate_trial_balance(schemes.first())
            trial_balance = tb
        except Exception as e:
            logger.warning('Trial balance generation failed: %s', e)
    data['trial_balance'] = trial_balance

    # ── Sector breakdown ─────────────────────────────────────────────
    sector_map = defaultdict(lambda: {'count': 0, 'invested': 0, 'fair_value': 0})
    for v in valuations:
        sec = v.get('sector', 'Other')
        sector_map[sec]['count'] += 1
        sector_map[sec]['invested'] += v.get('invested', 0)
        sector_map[sec]['fair_value'] += v.get('fair_value', 0)

    data['sector_breakdown'] = [{
        'sector': sec,
        'count': info['count'],
        'invested': info['invested'],
        'fair_value': info['fair_value'],
        'avg_moic': round(info['fair_value'] / info['invested'], 2) if info['invested'] > 0 else 0,
    } for sec, info in sorted(sector_map.items())]

    # ── Anomaly alerts ───────────────────────────────────────────────
    anomalies = MISAnomalyAlert.objects.filter(
        portfolio_company__organization=org, resolved=False
    ).select_related('portfolio_company').order_by('-severity', '-detected_at')[:20]
    data['anomaly_count'] = anomalies.count()
    data['anomalies'] = [{
        'company': a.portfolio_company.name,
        'type': a.get_anomaly_type_display(),
        'severity': a.severity.upper(),
        'description': a.description[:80],
        'detected': str(a.detected_at.date()),
    } for a in anomalies]

    return data


# ── Helper Functions ─────────────────────────────────────────────────────

def _generate_executive_summary(data):
    parts = []
    company_count = data.get('company_count', 0)
    aum = data.get('latest_aum')
    total_inv = data.get('total_invested')
    total_fv = data.get('total_fv')
    moic = data.get('aggregate_moic')

    if aum:
        parts.append(
            f'The fund manages an AUM of {_fmt_cr(aum)} '
            f'across {company_count} active portfolio companies.'
        )
    else:
        parts.append(f'The fund has {company_count} active portfolio companies.')

    if total_inv and total_fv:
        parts.append(
            f'Capital deployed: {_fmt_cr(total_inv)}, current fair value: '
            f'{_fmt_cr(total_fv)}, aggregate MOIC: {moic:.2f}x.'
        )

    anomaly_count = data.get('anomaly_count', 0)
    if anomaly_count > 0:
        parts.append(f'{anomaly_count} active anomaly alerts require attention.')
    else:
        parts.append('All companies within expected variance thresholds.')

    rev = data.get('agg_revenue')
    ebitda = data.get('agg_ebitda')
    if rev:
        parts.append(
            f'Aggregate portfolio revenue: {_fmt_cr(rev)}'
            + (f', EBITDA: {_fmt_cr(ebitda)}.' if ebitda else '.')
        )

    return ' '.join(parts) if parts else 'Executive summary will be populated once fund data is imported.'


def _generate_lp_letter(data, fund, report_date_str):
    """Generate a Quarterly LP Letter from fund data."""
    import calendar
    from datetime import date

    today = date.today()
    quarter = (today.month - 1) // 3 + 1
    quarter_end_month = quarter * 3
    quarter_label = f'Q{quarter} {today.year}'

    parts = []
    parts.append(f'<b>Dear Limited Partners,</b>')
    parts.append(f'<br/><br/>')
    parts.append(
        f'We are pleased to present the quarterly update for <b>{fund.name}</b> '
        f'for the period ending {report_date_str}.'
    )
    parts.append(f'<br/><br/>')

    # Fund performance summary
    aum = data.get('latest_aum')
    total_inv = data.get('total_invested')
    total_fv = data.get('total_fv')
    moic = data.get('aggregate_moic', 0)
    company_count = data.get('company_count', 0)

    parts.append(f'<b>Fund Performance:</b><br/>')
    if aum:
        parts.append(f'The fund currently manages an AUM of {_fmt_cr(aum)}. ')
    parts.append(
        f'As of this reporting date, the fund has deployed capital across '
        f'{company_count} portfolio companies. '
    )
    if total_inv and total_fv:
        parts.append(
            f'Total capital deployed stands at {_fmt_cr(total_inv)} with a current portfolio '
            f'fair value of {_fmt_cr(total_fv)}, translating to a gross MOIC of {moic:.2f}x. '
        )
    parts.append(f'<br/><br/>')

    # Portfolio highlights
    rev = data.get('agg_revenue')
    ebitda = data.get('agg_ebitda')
    pat = data.get('agg_pat')

    parts.append(f'<b>Portfolio Highlights:</b><br/>')
    if rev:
        parts.append(f'Aggregate portfolio revenue for the latest period: {_fmt_cr(rev)}. ')
    if ebitda:
        parts.append(f'Aggregate EBITDA: {_fmt_cr(ebitda)}. ')
    if pat:
        parts.append(f'Aggregate PAT: {_fmt_cr(pat)}. ')

    # Top performers
    pl = data.get('pl_consolidated', [])
    if pl:
        top = sorted([p for p in pl if p.get('revenue')], key=lambda x: x['revenue'] or 0, reverse=True)[:3]
        if top:
            names = ', '.join(t['company'] for t in top)
            parts.append(f'Top revenue contributors: {names}. ')
    parts.append(f'<br/><br/>')

    # Capital account
    capital_calls = data.get('capital_calls', [])
    distributions_data = data.get('distributions', [])
    parts.append(f'<b>Capital Activity:</b><br/>')
    total_called = sum(c.get('amount', 0) for c in capital_calls)
    total_distributed = sum(d.get('amount', 0) for d in distributions_data)
    parts.append(
        f'Total capital called to date: {_fmt_cr(total_called)}. '
        f'Total distributions to date: {_fmt_cr(total_distributed)}. '
    )
    investor_count = data.get('investor_count', 0)
    if investor_count:
        parts.append(f'The fund currently has {investor_count} investors. ')
    parts.append(f'<br/><br/>')

    # NAV
    nav_per_unit = data.get('nav_per_unit')
    if nav_per_unit:
        parts.append(f'<b>NAV Update:</b><br/>')
        parts.append(f'The latest NAV per unit stands at Rs.{float(nav_per_unit):,.2f}. ')
        parts.append(f'<br/><br/>')

    # Risk flags
    anomaly_count = data.get('anomaly_count', 0)
    parts.append(f'<b>Risk & Compliance:</b><br/>')
    if anomaly_count > 0:
        parts.append(f'{anomaly_count} anomaly alerts have been flagged and are under review. ')
    else:
        parts.append(
            'All portfolio companies are operating within expected variance thresholds. '
            'No material risk flags to report. '
        )
    parts.append(f'<br/><br/>')

    # Closing
    parts.append(
        'We remain committed to maximising value for our investors and will continue '
        'to actively engage with portfolio companies to drive operational improvements '
        'and growth. We look forward to sharing further updates in the next quarter.'
    )
    parts.append(f'<br/><br/>')
    parts.append(f'Warm regards,<br/>')
    parts.append(f'<b>Fund Management Team</b><br/>')
    parts.append(f'{fund.name}')

    return ''.join(parts)


def _build_screen_sections(data):
    """Build JSON sections for on-screen display — mirrors PDF content."""
    sections = []

    # 1. Fund Overview
    sections.append({
        'heading': '1. Fund Overview & Executive Summary',
        'type': 'kv_and_text',
        'text': _generate_executive_summary(data),
        'rows': [
            {'label': 'Portfolio Companies', 'value': str(data.get('company_count', 0))},
            {'label': 'Total AUM', 'value': _fmt_cr(data.get('latest_aum'))},
            {'label': 'Total Invested', 'value': _fmt_cr(data.get('total_invested'))},
            {'label': 'Total Fair Value', 'value': _fmt_cr(data.get('total_fv'))},
            {'label': 'Aggregate MOIC', 'value': _fmt_num(data.get('aggregate_moic'))},
            {'label': 'Revenue (Agg.)', 'value': _fmt_cr(data.get('agg_revenue'))},
            {'label': 'EBITDA (Agg.)', 'value': _fmt_cr(data.get('agg_ebitda'))},
        ]
    })

    # 2. Portfolio Company P&L
    pl = data.get('pl_consolidated', [])
    sections.append({
        'heading': '2. Portfolio Company P&L',
        'type': 'table',
        'headers': ['#', 'Company', 'Revenue (Cr)', 'EBITDA (Cr)', 'PAT (Cr)', 'EBITDA%', 'Period'],
        'table_rows': [
            [str(i + 1), r.get('company', ''), _fmt_cr(r.get('revenue')),
             _fmt_cr(r.get('ebitda')), _fmt_cr(r.get('pat')),
             _fmt_pct(r.get('ebitda_pct')), r.get('period', '')]
            for i, r in enumerate(pl)
        ],
        'summary': f'{len(pl)} companies',
    })

    # 3. Budget vs Actual
    bva = data.get('bva_summary', [])
    sections.append({
        'heading': '3. Budget vs Actual',
        'type': 'table',
        'headers': ['Company', 'Line Item', 'Budget (Cr)', 'Actual (Cr)', 'Variance (Cr)', 'Var%', 'Favorable'],
        'table_rows': [
            [r.get('company', ''), r.get('line_item', ''), _fmt_cr(r.get('budget')),
             _fmt_cr(r.get('actual')), _fmt_cr(r.get('variance')),
             _fmt_pct(r.get('variance_pct')),
             'Yes' if r.get('is_favorable') else ('No' if r.get('is_favorable') is False else '—')]
            for r in bva
        ],
        'summary': f'{len(bva)} records',
    })

    # 4. Valuations
    vals = data.get('valuations', [])
    sections.append({
        'heading': '4. Valuation Summary (IPEV)',
        'type': 'table',
        'headers': ['Company', 'Sector', 'Invested (Cr)', 'Fair Value (Cr)', 'MOIC', 'Methodology', 'Date'],
        'table_rows': [
            [v.get('company', ''), v.get('sector', '—'), _fmt_cr(v.get('invested')),
             _fmt_cr(v.get('fair_value')), _fmt_num(v.get('moic')),
             v.get('methodology', '—'), v.get('date', '')]
            for v in vals
        ],
        'summary': f'{len(vals)} valuations',
    })

    # 5. Capital Calls & Distributions
    cc = data.get('capital_calls', [])
    dist = data.get('distributions', [])
    lp = data.get('lp_accounts', [])
    sections.append({
        'heading': '5. Capital Account Statement',
        'type': 'multi_table',
        'sub_sections': [
            {
                'sub_heading': 'Capital Calls',
                'headers': ['Call #', 'Date', 'Amount (Cr)', 'Purpose', 'Status'],
                'table_rows': [
                    [str(c.get('call_number', '')), c.get('date', '—'), _fmt_cr(c.get('amount')),
                     c.get('purpose', '—'), c.get('status', '—')]
                    for c in cc
                ],
            },
            {
                'sub_heading': 'Distributions',
                'headers': ['Date', 'Amount (Cr)', 'Type'],
                'table_rows': [[d.get('date', '—'), _fmt_cr(d.get('amount')), d.get('type', '—')] for d in dist],
            },
            {
                'sub_heading': 'LP Capital Accounts',
                'headers': ['Investor', 'Committed (Cr)', 'Called (Cr)', 'Distributed (Cr)', 'Net Balance (Cr)', 'DPI'],
                'table_rows': [
                    [l.get('investor', ''), _fmt_cr(l.get('committed')), _fmt_cr(l.get('called')),
                     _fmt_cr(l.get('distributed')), _fmt_cr(l.get('net_balance')), _fmt_num(l.get('dpi'))]
                    for l in lp
                ],
            },
        ],
        'summary': f'Calls: {len(cc)} | Distributions: {len(dist)} | LP Accounts: {len(lp)}',
    })

    # 6. Anomaly Alerts
    anomalies = data.get('anomalies', [])
    sections.append({
        'heading': '6. Anomaly Alerts & Risk Flags',
        'type': 'table',
        'headers': ['Company', 'Type', 'Severity', 'Description', 'Detected'],
        'table_rows': [
            [a.get('company', ''), a.get('type', ''), a.get('severity', ''),
             a.get('description', ''), a.get('detected', '')]
            for a in anomalies
        ],
        'summary': f'{len(anomalies)} active alerts' if anomalies else 'No active alerts.',
    })

    return sections
