# Generated by Django 4.2.16 on 2026-04-22 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0003_alter_entity_entity_name_and_more'),
        ('accounts', '0003_fundos_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(help_text='Account code (e.g., 1000 = Cash, 1100 = Investments at Cost)', max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='accounts.organization')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='accounting.chartofaccounts')),
            ],
            options={
                'verbose_name_plural': 'chart of accounts',
                'ordering': ['account_code'],
                'unique_together': {('organization', 'account_code')},
            },
        ),
        migrations.CreateModel(
            name='CarriedInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_date', models.DateField(help_text='Date of carry calculation')),
                ('total_distributions', models.DecimalField(decimal_places=2, default=0, help_text='Total distributions to LPs to date', max_digits=18)),
                ('total_called_capital', models.DecimalField(decimal_places=2, default=0, help_text='Total capital called to date', max_digits=18)),
                ('preferred_return_amount', models.DecimalField(decimal_places=2, default=0, help_text='Hurdle cleared before carry kicks in', max_digits=18)),
                ('carry_base', models.DecimalField(decimal_places=2, default=0, help_text='Profit above hurdle subject to carry', max_digits=18)),
                ('carry_amount_gross', models.DecimalField(decimal_places=2, default=0, help_text="GP's carried interest entitlement (gross)", max_digits=18)),
                ('carry_amount_net', models.DecimalField(decimal_places=2, default=0, help_text="GP's carried interest after clawback provisions", max_digits=18)),
                ('gp_clawback_provision', models.DecimalField(decimal_places=2, default=0, help_text='Excess carry that may be returned to LPs', max_digits=18)),
                ('calculation_status', models.CharField(choices=[('indicative', 'Indicative'), ('crystallised', 'Crystallised'), ('paid', 'Paid')], default='indicative', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carried_interest_records', to='funds.scheme')),
            ],
            options={
                'ordering': ['scheme', '-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='NAVRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nav_date', models.DateField(help_text='Date of NAV calculation')),
                ('total_nav', models.DecimalField(decimal_places=2, help_text='Total NAV of the scheme (sum of all asset values)', max_digits=18)),
                ('total_units_outstanding', models.DecimalField(decimal_places=6, help_text='Total units outstanding for the scheme', max_digits=18)),
                ('nav_per_unit', models.DecimalField(decimal_places=6, help_text='SEBI: NAV per unit — must match depository records', max_digits=18)),
                ('investments_at_fair_value', models.DecimalField(decimal_places=2, default=0, help_text='Total fair value of all investments', max_digits=18)),
                ('cash_and_equivalents', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('receivables', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('management_fee_payable', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('other_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('depository_type', models.CharField(blank=True, choices=[('cdsl', 'CDSL'), ('nsdl', 'NSDL')], help_text='SEBI: CDSL or NSDL — for reconciliation', max_length=4)),
                ('depository_reconciled', models.BooleanField(db_index=True, default=False, help_text='SEBI: FALSE = incomplete for AAR filing')),
                ('depository_variance_amount', models.DecimalField(decimal_places=2, default=0, help_text='Difference if any — must be zero for clean AAR', max_digits=18)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_records', to='funds.scheme')),
            ],
            options={
                'ordering': ['scheme', '-nav_date'],
                'indexes': [models.Index(fields=['scheme', 'nav_date'], name='accounting__scheme__a15993_idx'), models.Index(fields=['depository_reconciled'], name='accounting__deposit_f2cbc1_idx')],
                'unique_together': {('scheme', 'nav_date')},
            },
        ),
        migrations.CreateModel(
            name='ManagementFeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('fee_basis_amount', models.DecimalField(decimal_places=2, help_text='The base amount (committed, called, or NAV) used to calculate fee', max_digits=18)),
                ('fee_rate', models.DecimalField(decimal_places=2, help_text='Annual fee rate (e.g., 2.00 = 2%)', max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Calculated management fee for this period', max_digits=18)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, help_text='GST on management fee (18% in India)', max_digits=18)),
                ('total_fee_with_gst', models.DecimalField(blank=True, decimal_places=2, help_text='fee_amount + gst_amount', max_digits=18, null=True)),
                ('fee_status', models.CharField(choices=[('calculated', 'Calculated'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='calculated', max_length=15)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_fee_schedules', to='funds.scheme')),
            ],
            options={
                'ordering': ['scheme', '-period_start'],
                'unique_together': {('scheme', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='FundLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_entry_number', models.CharField(help_text='Sequential JE number for audit trail', max_length=30)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_type', models.CharField(choices=[('capital_call', 'Capital Call'), ('investment', 'Investment'), ('distribution', 'Distribution'), ('management_fee', 'Management Fee'), ('carried_interest', 'Carried Interest'), ('valuation_adjustment', 'Valuation Adjustment'), ('expense', 'Expense'), ('other', 'Other')], max_length=25)),
                ('reference_id', models.UUIDField(blank=True, help_text='Links to source record (capital_call, investment, distribution, etc.)', null=True)),
                ('is_reversed', models.BooleanField(default=False, help_text='Whether this entry has been reversed (never delete ledger entries)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(help_text='Account credited', on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='accounting.chartofaccounts')),
                ('debit_account', models.ForeignKey(help_text='Account debited', on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='accounting.chartofaccounts')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='funds.scheme')),
            ],
            options={
                'ordering': ['scheme', '-entry_date', 'journal_entry_number'],
                'indexes': [models.Index(fields=['scheme', 'entry_date'], name='accounting__scheme__6524e0_idx'), models.Index(fields=['reference_type', 'reference_id'], name='accounting__referen_e3f3f6_idx')],
            },
        ),
    ]
