# Generated by Django 4.2.16 on 2026-04-21 06:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(default='2.0', max_length=10)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('fx_as_of', models.CharField(blank=True, max_length=10)),
                ('fx_rates', models.JSONField(blank=True, default=dict)),
                ('period_range', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('excel_parse', 'Excel Parse'), ('json_import', 'JSON Import'), ('manual', 'Manual')], default='excel_parse', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(db_index=True, max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('fund', 'Fund'), ('sector', 'Sector'), ('segment', 'Segment'), ('company', 'Company')], max_length=10)),
                ('parent_node_id', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('native_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('is_real', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('financials', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='portfolio.portfolionode')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='portfolio.portfoliosnapshot')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['snapshot', 'level'], name='portfolio_p_snapsho_efdb47_idx'), models.Index(fields=['snapshot', 'node_id'], name='portfolio_p_snapsho_6d2435_idx'), models.Index(fields=['snapshot', 'parent'], name='portfolio_p_snapsho_0cb30c_idx')],
                'unique_together': {('snapshot', 'node_id')},
            },
        ),
    ]
