# Generated by Django 4.2.16 on 2026-04-21 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('portfolio_node_id', models.CharField(blank=True, help_text='Links to PortfolioNode.node_id in the dashboard hierarchy', max_length=500)),
                ('instrument_type', models.CharField(choices=[('equity', 'Equity'), ('ccps', 'CCPS (Compulsorily Convertible Preference Shares)'), ('ccd', 'CCD (Compulsorily Convertible Debentures)'), ('ncd', 'NCD (Non-Convertible Debentures)'), ('safe', 'SAFE'), ('convertible_note', 'Convertible Note')], default='equity', max_length=20)),
                ('ownership_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Ownership percentage (e.g., 15.5000)', max_digits=7, null=True)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, help_text='Total amount invested (sum of tranches) in scheme currency', max_digits=18)),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('partially_exited', 'Partially Exited'), ('fully_exited', 'Fully Exited'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('board_seat', models.BooleanField(default=False, help_text='Whether the fund has a board seat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='funds.scheme')),
            ],
            options={
                'ordering': ['company_name'],
                'unique_together': {('scheme', 'company_name', 'instrument_type')},
            },
        ),
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., MRR, Burn Rate, Headcount', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('number', 'Number'), ('currency', 'Currency'), ('percent', 'Percentage'), ('ratio', 'Ratio'), ('boolean', 'Yes/No')], default='number', max_length=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_definitions', to='accounts.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ExitEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exit_type', models.CharField(choices=[('ipo', 'IPO'), ('merger_acquisition', 'Merger & Acquisition'), ('secondary_sale', 'Secondary Sale'), ('buyback', 'Buyback'), ('write_off', 'Write-Off')], max_length=20)),
                ('is_actual', models.BooleanField(default=False, help_text='True if this exit has actually occurred; False if it is a scenario/model')),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_valuation', models.DecimalField(blank=True, decimal_places=2, help_text='Company valuation at exit', max_digits=18, null=True)),
                ('proceeds', models.DecimalField(blank=True, decimal_places=2, help_text='Proceeds to the fund from this exit', max_digits=18, null=True)),
                ('realized_gain_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('moic', models.DecimalField(blank=True, decimal_places=2, help_text='Multiple on invested capital', max_digits=8, null=True)),
                ('irr_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Gross IRR %', max_digits=8, null=True)),
                ('buyer_name', models.CharField(blank=True, help_text='Acquirer/buyer (for M&A/secondary)', max_length=255)),
                ('assumptions', models.TextField(blank=True, help_text='Scenario assumptions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_scenarios', to='investments.investment')),
            ],
            options={
                'ordering': ['investment', '-exit_date'],
            },
        ),
        migrations.CreateModel(
            name='BoardMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_date', models.DateField()),
                ('meeting_number', models.PositiveIntegerField(blank=True, null=True)),
                ('agenda', models.TextField(blank=True)),
                ('minutes', models.TextField(blank=True)),
                ('attendees', models.JSONField(blank=True, default=list, help_text='List of attendee names')),
                ('resolutions', models.JSONField(blank=True, default=list, help_text='Key resolutions passed')),
                ('next_meeting_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, help_text='Attached board pack document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_meetings', to='documents.document')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_meetings', to='investments.investment')),
            ],
            options={
                'ordering': ['investment', '-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valuation_date', models.DateField()),
                ('methodology', models.CharField(choices=[('dcf', 'Discounted Cash Flow'), ('comparables', 'Market Comparables'), ('recent_transaction', 'Recent Transaction'), ('net_assets', 'Net Assets'), ('cost', 'Cost (at cost)')], max_length=20)),
                ('fair_value', models.DecimalField(decimal_places=2, help_text='Fair value of the investment in scheme currency', max_digits=18)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, help_text='Original cost basis for gain/loss calculation', max_digits=18, null=True)),
                ('unrealized_gain_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('multiple', models.DecimalField(blank=True, decimal_places=2, help_text='MOIC — fair_value / cost_basis', max_digits=8, null=True)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Discount rate used for DCF (%)', max_digits=5, null=True)),
                ('comparable_companies', models.JSONField(blank=True, default=list, help_text='List of comparable company names/multiples')),
                ('assumptions', models.TextField(blank=True, help_text='Valuation assumptions and notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='investments.investment')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['investment', '-valuation_date'],
                'unique_together': {('investment', 'valuation_date', 'methodology')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='First day of the reporting period (e.g., 2025-04-01)')),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='investments.investment')),
                ('kpi_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='investments.kpidefinition')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['investment', '-period'],
                'unique_together': {('investment', 'kpi_definition', 'period')},
            },
        ),
        migrations.CreateModel(
            name='InvestmentTranche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tranche_number', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date', models.DateField()),
                ('shares_acquired', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pre_money_valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('post_money_valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('round_name', models.CharField(blank=True, help_text='e.g., Series A, Series B, Bridge', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='investments.investment')),
            ],
            options={
                'ordering': ['investment', 'tranche_number'],
                'unique_together': {('investment', 'tranche_number')},
            },
        ),
    ]
