# Generated by Django 4.2.16 on 2026-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_fundos_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitevent',
            name='proceeds',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross proceeds to the fund from this exit', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='company_name',
            field=models.CharField(help_text='Denormalized company name for quick access', max_length=255),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='valuation_date',
            field=models.DateField(help_text='SEBI: Quarterly valuation required'),
        ),
    ]
