# Generated by Django 4.2.16 on 2026-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_valuation_ipev_fields_kpidefinition_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpidefinition',
            name='is_system_kpi',
            field=models.BooleanField(default=False, help_text='True for seeded system KPIs (not org-created) — prevents deletion'),
        ),
        migrations.AlterField(
            model_name='kpidefinition',
            name='sector_template',
            field=models.CharField(choices=[('generic', 'Generic'), ('saas', 'SaaS'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('nbfc', 'NBFC / Fintech'), ('consumer', 'Consumer'), ('realestate', 'Real Estate')], default='generic', help_text='Which sector template this KPI belongs to', max_length=15),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='corporate_action_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ratio for split/bonus (e.g., 2.0 for 2:1 split, 0.5 for 1:2 consolidation)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='corporate_action_type',
            field=models.CharField(choices=[('none', 'None'), ('stock_split', 'Stock Split'), ('bonus', 'Bonus Issue'), ('rights', 'Rights Issue'), ('dividend', 'Dividend'), ('buyback', 'Buyback')], default='none', help_text='Corporate action since last valuation — adjusts share count/price basis', max_length=15),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='dcf_terminal_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Terminal growth rate used in DCF (Level 3) — percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='dlom_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DLOM % applied to fair value (e.g., 20.00 = 20% discount)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='drhp_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valuation implied by DRHP filing (basis for Pre-IPO track)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='ipev_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1 — Quoted (Exchange Listed, CMP × shares)'), (2, 'Level 2 — Observable Inputs (Peer Multiples, IBBI certified)'), (3, 'Level 3 — Unobservable Inputs (DCF / Last Round, Board + IBBI certified)')], help_text='IPEV Level 1/2/3 classification — determines valuation method and certification', null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='is_pre_ipo',
            field=models.BooleanField(default=False, help_text='True if company has filed DRHP — enables Pre-IPO valuation track'),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='last_round_premium_discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Premium or discount to last round price (Level 3 last-round method)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='peer_multiples_used',
            field=models.JSONField(blank=True, default=list, help_text='List of peer EV/Revenue or EV/EBITDA multiples used in Level 2 valuation'),
        ),
    ]
