# Generated by Django 4.2.16 on 2026-05-06 11:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_investment_stage_irr'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='is_quoted',
            field=models.BooleanField(default=False, help_text='True if the company is publicly listed on a stock exchange'),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='listing_exchange',
            field=models.CharField(blank=True, help_text='Stock exchange: NSE, BSE, NYSE, NASDAQ, LSE, etc.', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyFinancials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='First day of the reporting month (e.g., 2025-04-01)')),
                ('gross_burn', models.DecimalField(blank=True, decimal_places=2, help_text='Total monthly cash outflow in Cr (expenses + capex)', max_digits=18, null=True)),
                ('net_burn', models.DecimalField(blank=True, decimal_places=2, help_text='Net monthly burn in Cr = gross burn minus revenue', max_digits=18, null=True)),
                ('cash_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Cash and equivalents at period end in Cr', max_digits=18, null=True)),
                ('runway_months', models.DecimalField(blank=True, decimal_places=1, help_text='Computed runway = cash_balance / net_burn. Null if burn is zero or not known.', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='investments.investment')),
                ('portfolio_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='investments.portfoliocompany')),
            ],
            options={
                'ordering': ['investment', '-period'],
                'unique_together': {('investment', 'period')},
            },
        ),
    ]
