# Generated by Django 4.2.16 on 2026-06-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_companyfinancials_is_quoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttranche',
            name='fully_diluted_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='investmenttranche',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='investmenttranche',
            name='natural_key',
            field=models.CharField(blank=True, db_index=True, help_text='Stable per-row identifier from the source file (Co.ID, instrument id, or row fingerprint). Lets re-imports update the same tranche instead of creating duplicates.', max_length=64),
        ),
        migrations.AddField(
            model_name='investmenttranche',
            name='ownership_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='valuation',
            name='source_tranche_key',
            field=models.CharField(blank=True, db_index=True, help_text='natural_key of the InvestmentTranche this valuation row came from. Lets round-level FV survive re-imports.', max_length=64),
        ),
    ]
