# Generated by Django 4.2.16 on 2026-06-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_alter_entity_gstin_alter_entity_organization_and_more'),
        ('investments', '0008_investmenttranche_fully_diluted_pct_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('scheme', 'company_name', 'instrument_type', 'stage')},
        ),
    ]
