# Generated by Django 4.2.16 on 2026-06-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_alter_investment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='co_investors',
            field=models.JSONField(blank=True, default=list, help_text='List of other investor/firm names that participated in the same rounds'),
        ),
    ]
