# Generated by Django 4.2.16 on 2026-06-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_portfoliocompany_co_investors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='methodology',
            field=models.CharField(choices=[('dcf', 'Discounted Cash Flow'), ('comparables', 'Market Comparables'), ('recent_transaction', 'Recent Transaction'), ('net_assets', 'Net Assets'), ('cost', 'Cost (at cost)'), ('option_pricing', 'Option Pricing Model')], max_length=100),
        ),
    ]
