# Generated by Django 4.2.16 on 2026-06-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_alter_valuation_methodology'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='moic',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Multiple on Invested Capital (e.g. 2.7500 means 2.75x). Computed in Phase 4 from tranches + exits + current FV.', max_digits=10, null=True),
        ),
    ]
