# Generated by Django 4.2.16 on 2026-07-06 04:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_portfoliocompany_is_aggregate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliocompany',
            options={'base_manager_name': 'all_objects', 'ordering': ['name'], 'verbose_name_plural': 'portfolio companies'},
        ),
        migrations.AlterModelManagers(
            name='portfoliocompany',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
