# Generated by Django 4.2.16 on 2026-07-06 08:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_alter_portfoliocompany_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'base_manager_name': 'all_objects', 'ordering': ['company_name']},
        ),
        migrations.AlterModelManagers(
            name='investment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
