# Generated by Django 4.2.16 on 2026-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketresearch', '0002_seed_142_opportunities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterpreset',
            name='filters',
            field=models.JSONField(default=dict, help_text='Saved filter values as JSON'),
        ),
        migrations.AlterField(
            model_name='marketopportunity',
            name='cagr_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Market CAGR %', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='marketopportunity',
            name='cagr_period',
            field=models.CharField(blank=True, help_text='e.g. 2024-2030', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketopportunity',
            name='description',
            field=models.TextField(help_text='1-2 paragraph overview'),
        ),
        migrations.AlterField(
            model_name='marketopportunity',
            name='investment_thesis',
            field=models.TextField(blank=True, help_text='1 para investment thesis'),
        ),
        migrations.AlterField(
            model_name='marketopportunity',
            name='is_seeded',
            field=models.BooleanField(default=True, help_text='True for system-seeded records'),
        ),
        migrations.AlterField(
            model_name='marketopportunity',
            name='key_players',
            field=models.TextField(blank=True, help_text='Top 5-10 players comma-separated'),
        ),
        migrations.AlterField(
            model_name='marketopportunity',
            name='name',
            field=models.CharField(help_text='Market opportunity name', max_length=200),
        ),
        migrations.AlterField(
            model_name='marketopportunity',
            name='sam_usd_bn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Serviceable Addressable Market in USD Billion', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketopportunity',
            name='tam_usd_bn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Addressable Market in USD Billion', max_digits=10, null=True),
        ),
    ]
