# Generated by Django 4.2.16 on 2026-05-05 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_kpidefinition_is_system_kpi_and_more'),
        ('documents', '0002_fundos_alignment'),
        ('funds', '0004_alter_entity_gstin_alter_entity_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ic_workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dealpipeline',
            new_name='ic_workflow_organiz_5bec4a_idx',
            old_name='ic_deal_org_stage_idx',
        ),
        migrations.AlterField(
            model_name='dealpipeline',
            name='equity_stake_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Proposed equity stake percentage', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dealpipeline',
            name='fund',
            field=models.ForeignKey(blank=True, help_text='Target fund for this investment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_pipeline', to='funds.fund'),
        ),
        migrations.AlterField(
            model_name='dealpipeline',
            name='linked_portfolio_company',
            field=models.ForeignKey(blank=True, help_text='Set once deal is closed and company is added to portfolio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_pipeline', to='investments.portfoliocompany'),
        ),
        migrations.AlterField(
            model_name='dealpipeline',
            name='pre_money_valuation_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre-money valuation in INR Cr', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='dealpipeline',
            name='proposed_investment_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Proposed investment amount in INR Cr', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='icdecision',
            name='approved_investment_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final approved investment amount (may differ from proposed)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='icdecision',
            name='capital_call_date',
            field=models.DateField(blank=True, help_text='Date capital call was issued', null=True),
        ),
        migrations.AlterField(
            model_name='icdecision',
            name='capital_call_triggered',
            field=models.BooleanField(default=False, help_text='True once capital call is issued to LPs for this investment'),
        ),
        migrations.AlterField(
            model_name='icdecision',
            name='conditions',
            field=models.TextField(blank=True, help_text='Conditions precedent to close (CP list)'),
        ),
        migrations.AlterField(
            model_name='icdecision',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='GP Partner who recorded the final decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ic_decisions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='icpresentation',
            name='deck_document',
            field=models.ForeignKey(blank=True, help_text='Investment thesis presentation deck', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ic_decks', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='icpresentation',
            name='memo_document',
            field=models.ForeignKey(blank=True, help_text='IC memo PDF in document vault', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ic_presentations', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='icpresentation',
            name='quorum_required',
            field=models.PositiveIntegerField(default=3, help_text='Minimum IC members required for quorum (default 3 of 5)'),
        ),
        migrations.AlterField(
            model_name='icvote',
            name='conditions',
            field=models.TextField(blank=True, help_text='Conditions attached to approval (e.g., "subject to due diligence on IP")'),
        ),
    ]
