# Generated by Django 4.2.16 on 2026-05-05 08:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form26qreturn',
            name='due_date',
            field=models.DateField(help_text='Statutory filing due date'),
        ),
        migrations.AlterField(
            model_name='form26qreturn',
            name='financial_year',
            field=models.CharField(help_text='e.g. FY2025', max_length=7),
        ),
        migrations.AlterField(
            model_name='tdswithholding',
            name='bsr_code',
            field=models.CharField(blank=True, help_text='Bank BSR code for challan', max_length=7),
        ),
        migrations.AlterField(
            model_name='tdswithholding',
            name='cess_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('4.000'), help_text='Health & Education Cess on tax', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tdswithholding',
            name='deductee_pan',
            field=models.CharField(blank=True, help_text='10-character PAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='tdswithholding',
            name='deductee_tan',
            field=models.CharField(blank=True, help_text='TAN of deductor', max_length=10),
        ),
        migrations.AlterField(
            model_name='tdswithholding',
            name='financial_year',
            field=models.CharField(blank=True, help_text='e.g. FY2025 (Apr 2024 — Mar 2025)', max_length=7),
        ),
        migrations.AlterField(
            model_name='tdswithholding',
            name='quarter',
            field=models.CharField(blank=True, help_text='e.g. Q1, Q2, Q3, Q4 of FY (Apr-Jun, Jul-Sep, Oct-Dec, Jan-Mar)', max_length=5),
        ),
        migrations.AlterField(
            model_name='tdswithholding',
            name='tds_rate_pct',
            field=models.DecimalField(decimal_places=3, help_text='TDS rate applied (e.g., 10.000 for 10%)', max_digits=5),
        ),
    ]
