# Generated by Django 4.2.16 on 2026-05-05 08:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_fundos_alignment'),
        ('funds', '0004_alter_entity_gstin_alter_entity_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundclose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clawbackcalculation',
            name='carry_rate_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='GP carry rate (default 20%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='clawbackcalculation',
            name='clawback_amount_inr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GP must return this to LPs if positive (overpaid); LP tops up if negative', max_digits=18),
        ),
        migrations.AlterField(
            model_name='clawbackcalculation',
            name='gp_carry_owed_inr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carry GP should receive = profit_above_hurdle × carry_rate', max_digits=18),
        ),
        migrations.AlterField(
            model_name='clawbackcalculation',
            name='gp_carry_paid_inr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carry already paid to GP during fund life', max_digits=18),
        ),
        migrations.AlterField(
            model_name='clawbackcalculation',
            name='hurdle_rate_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Preferred return hurdle (default 8% p.a.)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='clawbackcalculation',
            name='preferred_return_inr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hurdle return owed to LPs = drawn_capital × hurdle_rate × years', max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundcloseevent',
            name='final_nav_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final NAV at close date (INR Cr)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fundcloseevent',
            name='scheme',
            field=models.ForeignKey(blank=True, help_text='If scheme-level close; null = fund-level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_events', to='funds.scheme'),
        ),
        migrations.AlterField(
            model_name='fundcloseevent',
            name='total_invested_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total capital invested (INR Cr)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fundcloseevent',
            name='total_realized_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total realized proceeds from exits (INR Cr)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sebideregistration',
            name='application_date',
            field=models.DateField(blank=True, help_text='Date SEBI application filed', null=True),
        ),
        migrations.AlterField(
            model_name='sebideregistration',
            name='application_document',
            field=models.ForeignKey(blank=True, help_text='SEBI deregistration application PDF', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sebi_deregistration_applications', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='sebideregistration',
            name='compliance_officer',
            field=models.ForeignKey(blank=True, help_text='Compliance officer responsible for filing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sebideregistration',
            name='final_accounts_document',
            field=models.ForeignKey(blank=True, help_text='Final audited accounts PDF', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sebi_deregistration_final_accounts', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='sebideregistration',
            name='noc_date',
            field=models.DateField(blank=True, help_text='Date NOC from all LPs obtained', null=True),
        ),
    ]
