# Generated by Django 4.2.16 on 2026-05-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketpricefeed',
            new_name='marketdata__securit_c6a48a_idx',
            old_name='mktdata_security_date_idx',
        ),
    ]
