# Generated by Django 4.2.16 on 2026-04-22 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0003_alter_entity_entity_name_and_more'),
        ('investments', '0003_alter_exitevent_proceeds_and_more'),
        ('accounts', '0003_fundos_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(help_text='Should be encrypted at rest in production (pgcrypto AES-256)', max_length=50)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC code for Indian banks', max_length=11)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=11)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('nre', 'NRE'), ('nro', 'NRO'), ('fcnr', 'FCNR')], default='current', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.organization')),
            ],
            options={
                'ordering': ['-is_primary', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_number', models.PositiveIntegerField(help_text='Sequential call number per scheme (1, 2, 3...)')),
                ('call_date', models.DateField()),
                ('payment_due_date', models.DateField(db_index=True, help_text='Indexed for deadline tracking')),
                ('call_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of commitment being called (e.g., 25.00)', max_digits=5)),
                ('total_call_amount', models.DecimalField(decimal_places=2, help_text='Total amount being called across all LPs', max_digits=18)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of the capital call (investment, fees, expenses)')),
                ('call_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('paid', 'Paid'), ('defaulted', 'Defaulted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_calls', to='funds.scheme')),
            ],
            options={
                'ordering': ['scheme', 'call_number'],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commitment_amount', models.DecimalField(decimal_places=2, help_text='Total LP commitment (INR or scheme currency)', max_digits=18)),
                ('commitment_date', models.DateField(blank=True, null=True)),
                ('close_type', models.CharField(choices=[('first_close', 'First Close'), ('subsequent_close', 'Subsequent Close'), ('final_close', 'Final Close')], default='first_close', max_length=20)),
                ('units_allocated', models.DecimalField(blank=True, decimal_places=6, help_text='Units allocated to this LP', max_digits=18, null=True)),
                ('side_letter_exists', models.BooleanField(default=False, help_text='Whether this LP has differential rights via side letter')),
                ('subscription_form_url', models.URLField(blank=True, help_text='Link to signed subscription form', max_length=500)),
                ('commitment_status', models.CharField(choices=[('active', 'Active'), ('defaulted', 'Defaulted'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheme', 'investor'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distribution_number', models.PositiveIntegerField(help_text='Sequential distribution number per scheme')),
                ('distribution_date', models.DateField()),
                ('distribution_type', models.CharField(choices=[('return_of_capital', 'Return of Capital'), ('stcg', 'Short Term Capital Gain'), ('ltcg', 'Long Term Capital Gain'), ('interest', 'Interest Income'), ('dividend', 'Dividend'), ('carry', 'Carried Interest Distribution'), ('other', 'Other')], max_length=20)),
                ('total_gross_amount', models.DecimalField(decimal_places=2, help_text='Total gross distribution before TDS', max_digits=18)),
                ('total_tds_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total TDS withheld across all LPs', max_digits=18)),
                ('total_net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total net distribution after TDS', max_digits=18, null=True)),
                ('distribution_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('distributed', 'Distributed')], default='draft', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_exit_event', models.ForeignKey(blank=True, help_text='Link to the exit event that generated this distribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='investments.exitevent')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='funds.scheme')),
            ],
            options={
                'ordering': ['scheme', 'distribution_number'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_name', models.CharField(help_text='Legal name of the investor', max_length=255)),
                ('investor_type', models.CharField(choices=[('individual', 'Individual'), ('huf', 'HUF'), ('company', 'Company'), ('partnership', 'Partnership Firm'), ('llp', 'LLP'), ('trust', 'Trust'), ('society', 'Society'), ('aop', 'AOP/BOI'), ('fpi', 'Foreign Portfolio Investor'), ('fii', 'Foreign Institutional Investor'), ('nri', 'NRI'), ('bank', 'Bank'), ('insurance', 'Insurance Company'), ('pension', 'Pension Fund'), ('sovereign', 'Sovereign Wealth Fund'), ('endowment', 'Endowment'), ('fund_of_funds', 'Fund of Funds'), ('family_office', 'Family Office'), ('other', 'Other')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pan', models.CharField(blank=True, help_text='Mandatory for India-resident investors', max_length=10)),
                ('aadhaar_last_4', models.CharField(blank=True, help_text='Last 4 digits only — never store full Aadhaar', max_length=4)),
                ('ckyc_number', models.CharField(blank=True, help_text='CERSAI KYC number', max_length=14)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('kyc_completed_date', models.DateField(blank=True, null=True)),
                ('kyc_expiry_date', models.DateField(blank=True, null=True)),
                ('is_accredited_investor', models.BooleanField(default=False, help_text='SEBI: Required for LVF and accredited investor-only schemes')),
                ('accreditation_date', models.DateField(blank=True, null=True)),
                ('is_land_border_country', models.BooleanField(default=False, help_text='SEBI: Auto-flagged — AML Oct 2024 circular (China, Pakistan, Bangladesh, etc.)')),
                ('land_border_country_name', models.CharField(blank=True, help_text='SEBI: Country name if land-border flagged', max_length=100)),
                ('is_politically_exposed', models.BooleanField(default=False, help_text='PEP (Politically Exposed Person) flag — heightened due diligence required')),
                ('fatca_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('compliant', 'Compliant'), ('pending', 'Pending'), ('non_compliant', 'Non-Compliant')], default='not_applicable', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='accounts.organization')),
                ('portal_user', models.OneToOneField(blank=True, help_text='LP user who can log into the portal to view their data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
                ('primary_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_investors', to='lp.bankaccount')),
            ],
            options={
                'ordering': ['investor_name'],
            },
        ),
        migrations.CreateModel(
            name='DistributionLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text="This LP's share of gross distribution", max_digits=18)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=0, help_text='TDS rate applied (varies by distribution type + investor type)', max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, help_text='TDS withheld for this LP', max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount payable to LP after TDS', max_digits=18)),
                ('units_redeemed', models.DecimalField(blank=True, decimal_places=6, help_text='Units redeemed for this distribution', max_digits=18, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_line_items', to='lp.commitment')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='lp.distribution')),
            ],
            options={
                'ordering': ['distribution', 'commitment'],
            },
        ),
        migrations.AddField(
            model_name='commitment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='lp.investor'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='primary_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='lp.bankaccount'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='funds.scheme'),
        ),
        migrations.CreateModel(
            name='CapitalCallLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('called_amount', models.DecimalField(decimal_places=2, help_text="This LP's share of this call", max_digits=18)),
                ('cumulative_called_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of commitment called to date', max_digits=5, null=True)),
                ('units_allotted', models.DecimalField(blank=True, decimal_places=6, help_text='Units allotted to LP for this call', max_digits=18, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('defaulted', 'Defaulted')], default='pending', max_length=10)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('utr_number', models.CharField(blank=True, help_text='Unique Transaction Reference for payment verification', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capital_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='lp.capitalcall')),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_line_items', to='lp.commitment')),
            ],
            options={
                'ordering': ['capital_call', 'commitment'],
            },
        ),
        migrations.CreateModel(
            name='LPCapitalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField(db_index=True, help_text='Snapshot date — UNIQUE per commitment per date')),
                ('committed_capital', models.DecimalField(decimal_places=2, help_text='Total LP commitment', max_digits=18)),
                ('called_capital', models.DecimalField(decimal_places=2, default=0, help_text='Total drawn to date', max_digits=18)),
                ('uncalled_capital', models.DecimalField(decimal_places=2, default=0, help_text='Remaining commitment (committed - called)', max_digits=18)),
                ('distributed_capital', models.DecimalField(decimal_places=2, default=0, help_text='Total returned to LP to date', max_digits=18)),
                ('unrealized_value', models.DecimalField(decimal_places=2, default=0, help_text="FMV of portfolio at this date (LP's share)", max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='distributed_capital + unrealized_value', max_digits=18)),
                ('irr', models.DecimalField(blank=True, decimal_places=4, help_text='Since-inception IRR for this LP (e.g., 0.1520 = 15.20%)', max_digits=8, null=True)),
                ('tvpi', models.DecimalField(blank=True, decimal_places=4, help_text='Total Value to Paid-In multiple', max_digits=8, null=True)),
                ('dpi', models.DecimalField(blank=True, decimal_places=4, help_text='Distribution to Paid-In', max_digits=8, null=True)),
                ('rvpi', models.DecimalField(blank=True, decimal_places=4, help_text='Residual Value to Paid-In', max_digits=8, null=True)),
                ('moic', models.DecimalField(blank=True, decimal_places=4, help_text='Multiple on Invested Capital', max_digits=8, null=True)),
                ('units_held', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('management_fee_charged', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('carried_interest_charged', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_accounts', to='lp.commitment')),
            ],
            options={
                'ordering': ['commitment', '-as_of_date'],
                'indexes': [models.Index(fields=['as_of_date'], name='lp_lpcapita_as_of_d_c1db5a_idx')],
                'unique_together': {('commitment', 'as_of_date')},
            },
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['organization', 'investor_type'], name='lp_investor_organiz_6050b9_idx'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['organization', 'kyc_status'], name='lp_investor_organiz_4d0fd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together={('scheme', 'distribution_number')},
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['investor'], name='lp_commitme_investo_66a51f_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['scheme'], name='lp_commitme_scheme__a645ac_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalcalllineitem',
            index=models.Index(fields=['capital_call'], name='lp_capitalc_capital_19fe59_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalcalllineitem',
            index=models.Index(fields=['commitment'], name='lp_capitalc_commitm_681cdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='capitalcall',
            unique_together={('scheme', 'call_number')},
        ),
    ]
