# Generated by Django 4.2.16 on 2026-06-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='cumulative_called',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-LP cumulative drawdown to date (from Investors/LP-Master sheet)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='cumulative_distributed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-LP cumulative distributions received to date', max_digits=18, null=True),
        ),
    ]
