# Generated by Django 4.2.16 on 2026-06-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0002_commitment_cumulative_called_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='gp_carry_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Portion of this distribution paid as GP carry (when reported in source). Sum across all distributions = total carry GP has received to date — used to compute clawback when over-distribution occurs.', max_digits=18, null=True),
        ),
    ]
