# Generated by Django 4.2.16 on 2026-04-21 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ppm', 'Private Placement Memorandum'), ('subscription', 'Subscription Agreement'), ('contribution', 'Contribution Agreement'), ('capital_call', 'Capital Call Notice'), ('distribution', 'Distribution Notice'), ('valuation', 'Valuation Report'), ('audit', 'Audit Report'), ('compliance', 'Compliance Report'), ('financial', 'Financial Statement'), ('legal', 'Legal Document'), ('board', 'Board Resolution / Minutes'), ('kyc', 'KYC Document'), ('other', 'Other')], default='other', max_length=20)),
                ('visibility', models.CharField(choices=[('internal', 'Internal Only (GP)'), ('lp_visible', 'LP Visible'), ('public', 'Public')], default='internal', max_length=15)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(blank=True, help_text='Null for organization-level documents', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='funds.fund')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.organization')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='funds.scheme')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', '-created_at'], name='documents_d_organiz_6d035c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['fund', 'category'], name='documents_d_fund_id_cf3744_idx'),
        ),
    ]
