# Generated by Django 4.2.16 on 2026-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskscore', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyriskscore',
            new_name='riskscore_c_risk_ti_15cfab_idx',
            old_name='riskscore_tier_date_idx',
        ),
        migrations.AlterField(
            model_name='companyriskscore',
            name='flags',
            field=models.JSONField(blank=True, default=list, help_text='List of risk flags e.g. ["Cash runway < 6 months", "Revenue 30% below plan"]'),
        ),
    ]
