# Generated by Django 4.2.16 on 2026-04-24 05:39

import dataimport.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_fundos_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed With Errors'), ('failed', 'Failed')], default='pending', max_length=25)),
                ('progress_pct', models.IntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=500)),
                ('total_files', models.IntegerField(default=0)),
                ('completed_files', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of {file, section, row, error}')),
                ('result_summary', models.JSONField(blank=True, default=dict, help_text='Record counts per model after import')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=dataimport.models.import_file_path)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mapping', 'Column Mapping'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('column_mapping', models.JSONField(blank=True, default=dict, help_text='Gemini column mapping output per sheet')),
                ('gemini_confidence', models.FloatField(default=0.0)),
                ('sheet_names', models.JSONField(blank=True, default=list)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dataimport.importjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
