# Generated by Django 4.2.16 on 2026-04-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_alter_entity_gstin_alter_entity_organization_and_more'),
        ('dataimport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='fund',
            field=models.ForeignKey(blank=True, help_text='The fund created or updated by importing this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_files', to='funds.fund'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='fund_name',
            field=models.CharField(blank=True, help_text='Fund name extracted during import (for display even if fund is deleted)', max_length=255),
        ),
    ]
