# Generated by Django 4.2.16 on 2026-06-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0003_derivedmetric'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='derivedmetric',
            new_name='dataimport__scheme__69c483_idx',
            old_name='dataimport__scheme__idx',
        ),
        migrations.RenameIndex(
            model_name='derivedmetric',
            new_name='dataimport__organiz_fd7415_idx',
            old_name='dataimport__org__met_idx',
        ),
    ]
