# Generated by Django 4.2.16 on 2026-06-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_alter_entity_gstin_alter_entity_organization_and_more'),
        ('dataimport', '0004_rename_dataimport__scheme__idx_dataimport__scheme__69c483_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='derivedmetric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='derivedmetric',
            name='variant',
            field=models.CharField(blank=True, help_text='Semantic variant tag (e.g. "gross", "net", "pre_fee", "post_fee") for metrics that have multiple variants. Null when not applicable.', max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='derivedmetric',
            unique_together={('scheme', 'metric_key', 'variant')},
        ),
        migrations.AddIndex(
            model_name='derivedmetric',
            index=models.Index(fields=['scheme', 'metric_key', 'variant'], name='dataimport__scheme__3636cd_idx'),
        ),
    ]
