# Generated by Django 4.2.16 on 2026-06-09 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_account_locked_until_and_more'),
        ('funds', '0004_alter_entity_gstin_alter_entity_organization_and_more'),
        ('dataimport', '0005_derivedmetric_add_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(max_length=64)),
                ('variant', models.CharField(blank=True, help_text='gross/net/pre_fee/post_fee/... — null when the metric has no variant distinction.', max_length=32, null=True)),
                ('pass_id', models.CharField(choices=[('P35', 'Pass 3.5 — direct value imported'), ('P4', 'Pass 4 — catalogue formula derivation'), ('P8', 'Pass 8 — direct waterfall sheet read'), ('P9', 'Pass 9 — unified fund metrics compute')], max_length=8)),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('formula_expression', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('inputs_used', models.JSONField(blank=True, default=dict)),
                ('source_cells', models.JSONField(blank=True, default=list)),
                ('gemini_reasoning', models.TextField(blank=True)),
                ('arbiter_decision', models.CharField(blank=True, help_text='winner / rejected / superseded / identity_clamped / unused', max_length=24)),
                ('arbiter_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_candidates', to='accounts.organization')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_candidates', to='funds.scheme')),
                ('source_import_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_candidates', to='dataimport.importfile')),
            ],
            options={
                'ordering': ['scheme', 'metric_key', 'variant', 'pass_id'],
                'indexes': [models.Index(fields=['scheme', 'metric_key'], name='dataimport__scheme__943c28_idx'), models.Index(fields=['scheme', 'metric_key', 'variant'], name='dataimport__scheme__50ab56_idx'), models.Index(fields=['scheme', 'metric_key', 'variant', 'pass_id'], name='dataimport__scheme__e85479_idx')],
            },
        ),
    ]
