# Generated by Django 4.2.16 on 2026-06-09 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_alter_entity_gstin_alter_entity_organization_and_more'),
        ('accounts', '0006_alter_user_account_locked_until_and_more'),
        ('dataimport', '0006_metriccandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(help_text='Canonical metric key (moic, tvpi, dpi, rvpi, net_irr, nav, carry_base, carry_amount_gross, carry_amount_net, gp_clawback_provision, gp_catchup_amount, preferred_return_amount, return_of_capital_amount, total_committed_capital, total_called_capital, ...)', max_length=64)),
                ('value', models.DecimalField(blank=True, decimal_places=8, help_text='The metric value. Null when inputs were insufficient.', max_digits=24, null=True)),
                ('formula_expression', models.TextField(blank=True, help_text='The canonical formula used (textbook definition)')),
                ('inputs_used', models.JSONField(blank=True, default=dict, help_text='Map of anchor_name -> value used in the formula')),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='For each input anchor: {value, sheet, cell, reasoning}')),
                ('source', models.CharField(choices=[('extracted', 'Extracted directly from a cell in the document'), ('computed', 'Computed in Python from anchor values'), ('conflict', 'Stated value disagrees with computed value')], default='computed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_metrics', to='accounts.organization')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_metrics', to='funds.scheme')),
                ('source_import_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_metrics', to='dataimport.importfile')),
            ],
            options={
                'indexes': [models.Index(fields=['scheme', 'metric_key'], name='dataimport__scheme__c5f54d_idx'), models.Index(fields=['organization', 'metric_key'], name='dataimport__organiz_53365e_idx')],
                'unique_together': {('scheme', 'metric_key')},
            },
        ),
    ]
