# Generated by Django 4.2.16 on 2026-07-18 06:00

import dataimport.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_alter_user_account_locked_until_and_more'),
        ('dataimport', '0007_fundmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreIngestJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed With Errors'), ('failed', 'Failed')], default='pending', max_length=25)),
                ('progress_pct', models.IntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=500)),
                ('total_files', models.IntegerField(default=0)),
                ('output_file', models.CharField(blank=True, max_length=500)),
                ('output_name', models.CharField(blank=True, default='TFAI.xlsx', max_length=255)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preingest_jobs', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingest_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreIngestInputFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=dataimport.models.preingest_input_path)),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='dataimport.preingestjob')),
            ],
        ),
    ]
