# Generated by Django 4.2.16 on 2026-07-22 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_account_locked_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataimport', '0008_preingestjob_preingestinputfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreIngestAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('src', models.CharField(choices=[('human', 'Human confirmed'), ('auto', 'Auto resolved')], default='auto', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preingest_aliases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preingest_aliases', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization', 'key'],
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
