# Generated by Django 4.2.16 on 2026-04-20 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sebi_registration_number', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('cat_1', 'Category I'), ('cat_2', 'Category II'), ('cat_3', 'Category III')], default='cat_2', max_length=10)),
                ('structure_type', models.CharField(choices=[('trust', 'Trust'), ('company', 'Company'), ('llp', 'LLP')], default='trust', max_length=10)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('corpus_target', models.DecimalField(blank=True, decimal_places=2, help_text='Target corpus in base currency', max_digits=18, null=True)),
                ('base_currency', models.CharField(default='INR', max_length=3)),
                ('is_gift_city', models.BooleanField(default=False, help_text='GIFT City IFSC offshore AIF')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('winding_up', 'Winding Up')], default='active', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('vintage_year', models.PositiveIntegerField(blank=True, null=True)),
                ('first_close_date', models.DateField(blank=True, null=True)),
                ('final_close_date', models.DateField(blank=True, null=True)),
                ('scheme_size', models.DecimalField(blank=True, decimal_places=2, help_text='Scheme size in fund base currency', max_digits=18, null=True)),
                ('hurdle_rate_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Hurdle rate percentage (e.g., 8.00)', max_digits=5, null=True)),
                ('carry_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Carried interest percentage (e.g., 20.00)', max_digits=5, null=True)),
                ('carry_type', models.CharField(choices=[('european', 'European (Whole Fund)'), ('american', 'American (Deal-by-Deal)')], default='european', max_length=10)),
                ('management_fee_basis', models.CharField(choices=[('committed', 'Committed Capital'), ('called', 'Called Capital'), ('nav', 'NAV')], default='committed', max_length=10)),
                ('management_fee_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Annual management fee percentage (e.g., 2.00)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='funds.fund')),
            ],
            options={
                'ordering': ['fund', 'name'],
                'unique_together': {('fund', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Investment Manager'), ('trustee', 'Trustee'), ('sponsor', 'Sponsor'), ('custodian', 'Custodian'), ('statutory_auditor', 'Statutory Auditor'), ('legal_counsel', 'Legal Counsel'), ('registrar', 'Registrar & Transfer Agent')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('sebi_registration', models.CharField(blank=True, help_text='SEBI registration number (if applicable)', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='funds.fund')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['fund', 'role'],
                'unique_together': {('fund', 'role', 'name')},
            },
        ),
    ]
