# Generated by Django 4.2.16 on 2026-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_fundos_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_name',
            field=models.CharField(help_text='Legal name of the entity', max_length=255),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sebi_registration',
            field=models.CharField(blank=True, help_text='SEBI registration number (custodian, manager, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='fund',
            name='is_gift_city',
            field=models.BooleanField(default=False, help_text='GIFT City IFSC offshore AIF flag'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='sebi_registration_number',
            field=models.CharField(blank=True, help_text='SEBI AIF registration number — unique per fund', max_length=50),
        ),
    ]
