# Generated by Django 4.2.16 on 2026-04-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fundos_alignment'),
        ('funds', '0003_alter_entity_entity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='gstin',
            field=models.CharField(blank=True, help_text='GSTIN (Goods and Services Tax Identification Number)', max_length=15),
        ),
        migrations.AlterField(
            model_name='entity',
            name='organization',
            field=models.ForeignKey(help_text='Owning organization — entities are shared across funds within an org', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='pan',
            field=models.CharField(blank=True, help_text='PAN — mandatory for Indian entities', max_length=10),
        ),
        migrations.AlterField(
            model_name='fundcategory',
            name='leverage_permitted',
            field=models.BooleanField(default=False, help_text='Category III only — TRUE for hedge funds / leveraged strategies'),
        ),
        migrations.AlterField(
            model_name='fundcategory',
            name='sebi_category_code',
            field=models.CharField(help_text='SEBI category code — e.g., CAT_I_VCF, CAT_II, CAT_III_LVF', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='sponsor_commitment_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sponsor commitment as % of scheme size (SEBI min varies by category)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='tenure_years',
            field=models.PositiveIntegerField(blank=True, help_text='Scheme tenure in years (e.g., 10)', null=True),
        ),
    ]
