# Generated by Django 4.2.16 on 2026-06-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_alter_entity_gstin_alter_entity_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='gp_holdback_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GP carry escrow holdback as % of distributed carry (industry default 20%; LPA-specific value extracted from Fund_Overview "Clawback Provision" / "Escrow Holdback %" cell).', max_digits=5, null=True),
        ),
    ]
